### ISSUE TITLE
Add Docs

### ISSUE THREAD

**Issue by KStasi** [airgap-it/beacon-sdk#1]
For now, the single way to understand how to use sdk is to look at source code and example directory. That's quite inconvenient. 

It would be fine to see api page with classes and method descriptions along with examples (as the separate source or at least wiki page).

**Comment by AndreasGassmann** [comment]
The SDK is still under heavy development and there are a lot of breaking changes. Once the API is more or less finalised, we'll definitely add some for of documentation.

**Comment by AndreasGassmann** [comment]
There is now some documentation available here: https://docs.walletbeacon.io/

So far it's just some examples and a getting started section, but we'll add more soon.
