### ISSUE TITLE
Thanos wallet installed from the Firefox Add-ons store is not recognized by Beacon

### ISSUE THREAD

**Issue by lourenc** [airgap-it/beacon-sdk#107]
**Describe the bug (current behavior)**
If Thanos wallet is installed from the Firefox Browser Add-ons store, it's not automatically recognized, and it's shown as a duplicated wallet in the list.

It seems to happen because there's a different extension `id` in Firefox. And Thanos Chrome's is the only id currently recognized by Beacon: https://github.com/airgap-it/beacon-sdk/blob/4603487d81c37247b8524bbf2c9cd6210d94cad0/scripts/generate-wallet-list.ts#L8

**To Reproduce**
1. Install Thanos wallet into Firefox browser from the Firefox Add-ons store
2. Open dApp
3. Try connecting to dApp and wait for a connection window
4. See the duplicated Thanos wallet in the wallet list

**Expected (correct) behavior**
Thanos wallet on Firefox is recognized and highlighted in the wallet list of the Beacon connection modal.

**Screenshots and/or logs**
![image](https://user-images.githubusercontent.com/6189971/102650199-2dc71b80-4173-11eb-8eec-cb782ac11db3.png)

**Environment**
 - Browser: Firefox

**Additional Context**
The current correct Firefox extension id for Thanos is: `34ac229e-1cf5-4e4c-8a77-988155c4360f`

**Comment by AndreasGassmann** [comment]
Hey, sorry for the late reply.

That's true, we currently only consider chrome extension IDs. We'll have to add others as well.

**Comment by lourenc** [comment]
Thanks a lot!
