### ISSUE TITLE
Origination.d.ts has a kind of Delegation

### ISSUE THREAD

**Issue by ungarson** [airgap-it/beacon-sdk#120]
<img width="981" alt="Screenshot 2021-01-08 at 20 47 57" src="https://user-images.githubusercontent.com/13982759/104048545-6dbe7300-51f4-11eb-973b-e6f0e251542c.png">
<img width="981" alt="Screenshot 2021-01-08 at 20 48 15" src="https://user-images.githubusercontent.com/13982759/104048550-70b96380-51f4-11eb-9d3e-dd15129feb49.png">

In the picture above Origination and Delegation have the same kind of operation, which is TezosOperationType.DELEGATION. I guess, Origination is supposed to have TezosOperationType.ORIGINATION.

**Comment by AndreasGassmann** [comment]
This will be included in the `2.0.2` release.
