### ISSUE TITLE
FR: dark theme or general theming support

### ISSUE THREAD

**Issue by martinpospech** [airgap-it/beacon-sdk#121]
**Summary**
Dark theme for Beacon dialogs.

**Describe the expected behaviour**
It should be possible for an app to specify whether to use a dark theme for Beacon dialogs.

**Describe your use case**
Apps or websites with dark theme would benefit from having dark themed Beacon dialogs. Mixing white dialogs with dark theme is visually unpleasant and therefore undesirable.

**Comment by AndreasGassmann** [comment]
Thanks for the suggestion. We will include this in one of our next releases.

**Comment by AndreasGassmann** [comment]
Done in https://github.com/airgap-it/beacon-sdk/pull/126, it will be included in the 2.2.0 release
