### ISSUE TITLE
Introduce new error types

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#131]
**Summary**
The `beacon-sdk` currently supports a small number of errors that a wallet can return to a dApp. We should extend the list of possible error messages to allow wallets to return more meaningful errors to the developer.

One example would be a `OPERATION_NOT_SUPPORTED`, for example when signing is not supported.

**Comment by ungarson** [comment]
@AndreasGassmann hi, I just wanted to create a similar enhancement request, thanks.
I noticed that when you close a window with opened wallet and when you reject an operation, they both return AbortedBeaconError error. Would be cool if these were two different errors, I guess.

<img width="441" alt="Screenshot 2021-01-22 at 19 09 20" src="https://user-images.githubusercontent.com/13982759/105515485-cbb78400-5ce5-11eb-9021-cd1c9cfc82fd.png">

**Comment by AndreasGassmann** [comment]
What is the use case where you need to differentiate the 2?

**Comment by ungarson** [comment]
@AndreasGassmann I need to show a user two different error messages

**Comment by AndreasGassmann** [comment]
I don't see how those 2 events differ from an enduser perspective. In the end, the user aborted the request, it doesn't matter if he chose the "reject" button or decided to close the window, unless you make assumptions about their intent, which I'm not sure if you can.

How would your two error messages look like?
