### ISSUE TITLE
Problem with active account

### ISSUE THREAD

**Issue by ungarson** [airgap-it/beacon-sdk#132]
Earlier using version 2.0.1 I could set the value of `beacon:active-account` (in localStorage) to undefined, and beacon-sdk would show me all available wallets instead of showing me the latest version. How can I achieve the same thing in the current version? Even if I set `beacon:active-account` to undefined right now, it still shows me the latest used wallet.
Btw maybe I can achieve it without interacting with local storage? Haven't found anything in the docs, let me know please if it's possible.

**Comment by AndreasGassmann** [comment]
This can be achieved by using `await client.clearActiveAccount()` (pre `2.1.0` it was `await client.setActiveAccount()`).

In `2.1.0` we introduced a change that would not only persist the active account, but also the active peer. This change improved the case when a user connects a wallet, but then denies the permission request and tries again (potentially after a page refresh). Previously, this would trigger a completely new "pairing flow", but in 2.1.0 the peer was persisted so it would directly send the permission request to the same peer again.

So you would now also have to clear `beacon:active-peer` to get the previous behaviour. But in any case, you should _never_ alter the local storage directly. If you find a use case that is not covered by the `DappClient` methods, please let me know.

**Comment by ungarson** [comment]
@AndreasGassmann, thanks for the reply. I am not sure why but even though I've cleared an active account, I still get it.
This is the code I use:
```
      let wallet = new DAppClient({
        name: '123456',
      });
      const networkMap = // ...
      const type = // ...
      await wallet.clearActiveAccount();
      console.log('active account is cleared');
      await wallet.requestPermissions({ network: { type, rpcUrl } });
      return wallet;
```

And this is the result:

<video src="https://user-images.githubusercontent.com/13982759/105704521-fd1b9400-5f1f-11eb-9379-5437fe207a09.mov"/>

Is it a bug or do I miss something? 😬

**Comment by AndreasGassmann** [comment]
That's very odd. I just tried to reproduce it, but for me it works fine.

In our test dApp, I do this:

```
      const requestPermission = () => {
        client
          .requestPermissions()
          .then((permissions) => {
            console.log('permissions', permissions)
            updateActiveAccount()
          })
          .catch((error) => {
            console.log('error during permission request', error)
          })
      }

      document
        .getElementById('clearActiveAccountAndPermissionRequest')
        .addEventListener('click', async () => {
          await client.clearActiveAccount()

          requestPermission()
          updateActiveAccount()
        })
```

Can you add a `setTimeout` and delay the permission request for 1 second, just so we know if it's a timing issue?

**Comment by AndreasGassmann** [comment]
I just noticed that you create a new `DAppClient` in your `getWallet` method. Is this method only called once, or multiple times?

You should only ever have one `DAppClient` instance active on your page. https://github.com/airgap-it/beacon-sdk/issues/112

**Comment by ungarson** [comment]
@AndreasGassmann thanks, indeed, this method could have been called multiple times, I have fixed this, and now I clearing active account works 😊

**Comment by ungarson** [comment]
@AndreasGassmann what if I want to activate previously used account, is there any way to approach this?

**Comment by ungarson** [comment]
@AndreasGassmann is there any way I can do `client.setActiveAccount(previouslyUsedAccount)` after clearing active account without accessing local storage?

**Comment by AndreasGassmann** [comment]
Glad to hear your issue has been resolved.

Yes, you can re-set the active account to any previously paired account. All you have to do is get the list of accounts with `const accounts = await client.getAccounts()`, and then pass the account you want to the set method eg. `client.setActiveAccount(accounts[0])`
