### ISSUE TITLE
Closeable when clicked outside the modal

### ISSUE THREAD

**Issue by ungarson** [airgap-it/beacon-sdk#133]
Could you please make it closeable? This is a common UX practice, so it would be very useful for the users

<img width="700" alt="Screenshot 2021-01-22 at 21 18 46" src="https://user-images.githubusercontent.com/13982759/105529510-8d2ac500-5cf7-11eb-95e6-b4a431e752f4.png">

**Comment by AndreasGassmann** [comment]
Done, will be included in 2.2.0
