### ISSUE TITLE
Investigate "build issues"

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#138]
**Describe the bug (current behavior)**
There have been reports that the SDK does not work in some conditions, eg. when webpack is not used.

**Expected (correct) behavior**
The SDK should work, regardless of the build system.

**Screenshots and/or logs**
https://github.com/airgap-it/beacon-sdk/issues/124

**Comment by thecatrine** [comment]
I looked into this while trying to get the Taquito wallet example to run with parcel. I suspect at least the bug with sodium is being caused by a compatibility issue with the typescript compiler with `import * as blah from 'blah'` imports vs `import blah from 'blah'` imports wiith default exports.
The sodium object imported fine, but all the utils were namespaced under `sodium.default.what_have_you`

I got a local version of the library to work with parcel/the example by replacing the imports  with `import sodium from 'libsodium-wrappers'` and adding `"allowSyntheticDefaultImports": true,` to tsconfig.json

**Comment by thecatrine** [comment]
Interestingly, parcel 1 builds it successfully and parcel 2 does not. I think parcel 2 switched from tsc to babel, and there's different default import behavior potentially.

**Comment by roxaneletourneau** [comment]
Hi @AndreasGassmann 
We get a server build issue on our website that is built with Docusaurus and it seems to be related to the SDK also.

**Comment by PureSpider** [comment]
This is still broken when trying to use this library with parcel:
```
TypeError: sodium.crypto_generichash is not a function
    at Object.<anonymous> (index.fd532818.js:92560)
    at step (index.fd532818.js:92493)
    at Object.next (index.fd532818.js:92442)
    at fulfilled (index.fd532818.js:92405)
```

**Comment by PureSpider** [comment]
@thecatrine how did you manage to get it to build with parcel 1? Which version did you try with, exactly?

**Comment by dribnet** [comment]
For me parcel 1 was working fine up to beacon-sdk version 6.4.0-ledger.0, but after that the library is unusable with the same reported bug:

<img width="511" alt="Screen Shot 2021-06-18 at 10 28 05 AM" src="https://user-images.githubusercontent.com/945979/122479994-226c8400-d020-11eb-8613-f23f8df722cd.png">

@mattdesl provides a nice test case for this issue at ecadlabs/taquito#882

**Comment by i3games** [comment]
> Interestingly, parcel 1 builds it successfully and parcel 2 does not. I think parcel 2 switched from tsc to babel, and there's different default import behavior potentially.

I am using parcel 1.12.5 and it does *not* build.

**Comment by clemsos** [comment]
Is there any updates on this? I am struggling to get the sdk to work with my bundler (vitejs) but still get `TypeError: sodium.crypto_generichash is not a function`. Many thanks !

**Comment by thecatrine** [comment]
@clemsos Are you able to build with the fork mentioned in the PR above?

**Comment by BerkeleyTrue** [comment]
seeing the same issue in a clojurescript shadow-clj project.
![image](https://user-images.githubusercontent.com/6775919/142551290-fd39e3f3-ab65-4702-8a09-560ec38e230c.png)

**Comment by AndreasGassmann** [comment]
@BerkeleyTrue Can you try to install version `2.4.0-beta.2`?

**Comment by BerkeleyTrue** [comment]
@AndreasGassmann yup, looks like it's fixed

**Comment by souljorje** [comment]
@AndreasGassmann also fixed for me (vite + vue).
```
"vite": "^2.7.3"
"@airgap/beacon-sdk": "^2.4.0-beta.2"
"@taquito/beacon-wallet": "^10.2.1"
"@taquito/taquito": "^10.2.1"
```
More: https://github.com/ecadlabs/taquito/issues/882#issuecomment-999753605

**Comment by mikesizz** [comment]
Bump!

What is the status of this issue? I am using a fresh install of the taquito and beacon-wallet sub packages and I am hitting this issue.

If I downgrade to the mentioned version 6 everything works fine, but with any upgrades it busts. This seems like a total deal breaker as I'm using no tools or frameworks. Literally just fresh package installs with a fresh browserify install. Help!

Also, all of the documentation links are dead. It feels impossible to get started developing with this lib please help!

**Comment by thecatrine** [comment]
@mikesizz are you on the beta version mentioned above? Can you share a minimal example that breaks?

**Comment by mikesizz** [comment]
Steps to reproduce:
- `npm init` new project
- `npm install` the following
```
"@airgap/beacon-sdk": "^2.4.0-beta.2"
"@taquito/beacon-wallet": "^9.1.0"
"@taquito/taquito": "^9.1.0"
"browserify": "^17.0.0"
```
- add the following file `dep.entry.js`
```
"use strict";

(function () {
  window.TezosToolkit = require('@taquito/taquito').TezosToolkit;
  window.BeaconWallet = require('@taquito/beacon-wallet').BeaconWallet;
})();
```
- add the npm command `./node_modules/.bin/browserify ./dep.entry.js > ./public/dapp/deps.js`
- add front end js file with following contents
```
 var BeaconWallet = window.BeaconWallet;
 var wallet = new BeaconWallet({
     name: 'TEST',
 });
```
- open file in browser and get the error `TypeError: sodium.crypto_generichash is not a function`

If I switch to the version `6.4.0-ledger.0` for taquito and beacon-wallet it works fine.

**Comment by AndreasGassmann** [comment]
If you don't use a framework or modern build tools, we have a browserified of the beacon-sdk available: https://unpkg.com/@airgap/beacon-sdk@2.3.9/dist/walletbeacon.min.js

Taquito also has a browserified version available, but I'm not sure if it includes the beacon-sdk: https://unpkg.com/@taquito/taquito@11.1.0/dist/taquito.min.js

I am not familiar with browserify, but in our build pipeline, we have to use the ES5 code for the browserify build. The ES5 code is also shipped as part of the beacon-sdk npm module, it is located in the `dist/cjs` folder.

My assumption is that your project still uses beacon-sdk < `2.4.0-beta.2` because taquito has a dependency on `2.x.x`, which does not match beta versions. You can check your package-lock.json file to see if an old version of the beacon-sdk is still installed. If it is, try forcing the newer version and see if that works. (see https://stackoverflow.com/questions/58065817/npm-force-package-lock-to-update-a-sub-dependency-package)

> Also, all of the documentation links are dead.
Both https://docs.walletbeacon.io/ and https://typedocs.walletbeacon.io/ are working, AFAIK we do not have any other documentation.

**Comment by mikesizz** [comment]
Thanks @AndreasGassmann. My apologies about the docs comment! It was late and I got mixed up with which repo I was commenting on (Taquito's docs are broken atm).

I really appreciate the CDN links; I'll use those for now. I will probably use the same approach you describe regarding using ES5 code. From my understanding this issue stems from using the newer JS `import` statement?

In any event, I hope we can find some resolution on this for the long term.

**Comment by HirotakaAseishi** [comment]
I have the same issue using vite(SvelteKit).

console error is
sodium3.randombytes_buf is not a function

I don't be familiar with vite but it may fail to build or read wrong path. 
is this vite problem?

<img width="1127" alt="Screen Shot 2022-01-12 at 23 19 41" src="https://user-images.githubusercontent.com/10542845/149158791-b2c0b1f9-8734-4a21-985f-8208320b7d5e.png">

**Comment by mikesizz** [comment]
I don't use svelte buy I've seen others mention this issue with svelte and vite.

I'll see if I can find the thread...

**Comment by mikesizz** [comment]
That was fast, haha. Sorry it was vue not svelte, but they do mention vite, so hopefully this may help you.

https://github.com/ecadlabs/taquito/issues/882#issuecomment-999753605

**Comment by HirotakaAseishi** [comment]
@mikesizz Thank you for the comment! It's the same problem as you say. I've tried some adjustment, but it's still not working with sveltekit.

I'll continute to try. thank you!

**Comment by mikesizz** [comment]
I was never able to solve it. For now I'm using the CDN version until the project is ready for production.

At that point my plan is to investigate using parcel in the ci/cd pipeline to bundle up this particular dep until a solution presents itself.

It's beyond suboptimal to have a totally different build tool just for this dependency, but I don't really see a solution for now. 🤷‍♂️

**Comment by fredcy** [comment]
> That was fast, haha. Sorry it was vue not svelte, but they do mention vite, so hopefully this may help you.
> 
> [ecadlabs/taquito#882 (comment)](https://github.com/ecadlabs/taquito/issues/882#issuecomment-999753605)

The hints in that taquito issue got me past the "TypeError: sodium.crypto_generichash is not a function" error.

But the need to use different Beacon modules based on the dev vs build environment (for vite) suggests that something is still off with how Beacon-SDK builds and distributes its modules.

**Comment by AndreasGassmann** [comment]
Libsodium has been removed and was replaced by @stablelib a while ago, so those issues should no longer exist.
