### ISSUE TITLE
Provide an option to show the QR code instead of automatically connecting to a wallet

### ISSUE THREAD

**Issue by gretzke** [airgap-it/beacon-sdk#15]
From the documentation

```
The beacon-sdk will automatically try to establish a connection.

If a chrome extension is detected, all requests will be directed to the chrome extension.

If no chrome extension is detected, it will fall back to the beacon p2p transport layer, which means that a QR code is shown that has to be scanned by a compatible wallet. As of now, the only mobile wallet with Beacon supprt is AirGap Wallet. You can download the app from Github or the Play Store (Android) or the AppStore (iOS).
```

When requesting access while I have the Thanos Wallet installed, the beacon wallet automatically connects to the Thanos wallet. I want to also be able to have the option or to force show the QR code in case I want to use the AirGap wallet.

**Comment by AndreasGassmann** [comment]
Hi. Sorry for not getting back to you on this. As a user, there is currently nothing you can do in this case other than disabling Thanos. As a developer you should be able to force the P2PTransport by passing it in the DAppClient constructor.

We did take this feedback into account when refining the tzip10 specs. This will be possible in v2 (which will come out in a couple of weeks).

**Comment by AndreasGassmann** [comment]
This is now working in v2, which will be released soon. Please try it out there and give us feedback if that solves your usecase.
