### ISSUE TITLE
Building client with rollup and typescript results in incorrect call to qrcode module

### ISSUE THREAD

**Issue by fredcy** [airgap-it/beacon-sdk#170]
**Describe the bug (current behavior)**
When I build a BeaconSDK client using the Rollup bundler and Typescript, I get an warning during compilation and a blocking error when I run the client application.

**To Reproduce**

1. Clone the repo at https://gitlab.com/fredcy/beacon-issue-1.git

2. Build the application:

```
npm install
npm run build
```

3. Serve the application

```
npm run serve
```

4. Visit http://localhost:5000 and open the console.

**Expected (correct) behavior**
I expect the app to compile cleanly. 

I expect the app to execute the Beacon permissionRequest flow, including the wallet chooser and permission-request in the wallet.

**Actual behavior**

The output during compilation reports a problem:

```
(!) Cannot call a namespace ('qrcode')
node_modules/@airgap/beacon-sdk/dist/esm/utils/qr.js: (13:15)
11:     const typeNumber = 0;
12:     const errorCorrectionLevel = 'L';
13:     const qr = qrcode(typeNumber, errorCorrectionLevel);
                   ^
14:     if (payload.length > 500) {
15:         logger.warn('getQrData', 'The size of the payload in the QR code is quite long and some devices might not be able to scan it anymore. To reduce the QR size, try using a shorter "name", "appUrl" and "iconUrl"');

```

And when I run the app in the browser, it hangs at the client.requestPermission() call. No wallet chooser appears, possibly because the QR code can't be created.

**Environment**

- Device: MacBook Pro
 - OS: MacOS 10.15.7
 - Browser: latest Firefox and Chrome

**Additional context**
The rollup.config.js has a section commented out that if applied patches the Beacon code so that it works.

**Comment by AndreasGassmann** [comment]
This is probably related to https://github.com/airgap-it/beacon-sdk/issues/124 and https://github.com/airgap-it/beacon-sdk/issues/138

I'll look into it now

**Comment by fredcy** [comment]
I think it might indeed be related. Some older modules seem to export `default` in a way that newer code doesn't import properly unless it accesses via `old_module.default` rather than just `old_module`. I've seen this with libsodium-wrappers and now with qrcode-generator. Some packaging flows such as what beacon-vue-example uses do some kind of transformation that makes this work. Others that I have tried using Parcel.js and now Rollup.js do not, at least as far as I have worked out. Disclaimer: I am new to modern JS modules and packaging and may be missing something obvious here to work around the problem.

The patch in my rollup.config.js modifies https://github.com/airgap-it/beacon-sdk/blob/551ec847d9339922cfb0d1382f82d639bc965d6d/src/utils/qr.ts#L15 to call `qrcode.default()` rather than just `qrcode()` per what I found at https://github.com/kazuhikoarase/qrcode-generator/issues/62

**Comment by AndreasGassmann** [comment]
I just released 2.2.2-beta.0 which has some changes in the build script: https://github.com/airgap-it/beacon-sdk/pull/171

Can you try it out and see if it works?

**Comment by AndreasGassmann** [comment]
Sadly it did not work. I'll give it another try.

**Comment by fredcy** [comment]
Looking at my old rollup.config.js, I would do this in the plugins section:

```
	// Monkey-patch Beacon code. Without this I get a rollup
	// error about "Cannot call a namespace ('qrcode')", and the call to
	// requestPermissions() hangs at app runtime.
	replace({
	    "qr = qrcode(": "qr = qrcode.default(",
	    delimiters: ["", ""],
	    include: "node_modules/@airgap/beacon-sdk/**",
	}),
```

**Comment by souljorje** [comment]
@fredcy yep, eventually I did something kinda this, valid for beacon-sdk@3

```js
// vite.config.js

import replace from 'rollup-plugin-re';

export default {
    plugins: [
        {
            ...replace({
                include: ['node_modules/@airgap/**'],
                replaces: {
                    "import * as qrcode from 'qrcode-generator';": "import  qrcode from 'qrcode-generator';",
                },
            }),
            apply: 'build',
            enforce: 'pre',
        },
    ],
};

        
```

**Comment by PureSpider** [comment]
@souljorje sadly, this does not work for me using version 3.1.4 of @airgap/beacon-dapp, and the QR code is shown in dev, but not prod - which is the same situation as when _not_ using the workaround.

Do you know if there is anything I can do to remedy this?

This is my current `vite.config.ts`:
```ts
import { defineConfig } from "vite";
import path from "path";
import vue from "@vitejs/plugin-vue";
import replace from "rollup-plugin-re";

// https://vitejs.dev/config/
export default ({ command }) => {
    const isBuild = command === "build";

    return defineConfig({
        base: "./",
        plugins: [
            vue(),
            {
                ...replace({
                    include: ["node_modules/@airgap/**"],
                    replaces: {
                        "import * as qrcode from 'qrcode-generator';": "import qrcode from 'qrcode-generator';",
                    },
                }),
                apply: "build",
                enforce: "pre",
            },
        ],
        build: {
            target: "esnext",
            commonjsOptions: {
                transformMixedEsModules: true,
            },
        },
        resolve: {
            alias: {
                // dedupe @airgap/beacon-dapp
                // I almost have no idea why it needs `cjs` on dev and `esm` on build, but this is how it works 🤷‍♂️
                "@airgap/beacon-dapp": path.resolve(path.resolve(), `./node_modules/@airgap/beacon-dapp/dist/${isBuild ? "esm" : "cjs"}/index.js`),
                // polyfills
                "readable-stream": "vite-compatible-readable-stream",
                stream: "vite-compatible-readable-stream",
            },
        },
    });
};
```

**Comment by 852Kerfunkle** [comment]
@AndreasGassmann what's the argument against using `allowSyntheticDefaultImports` and importing the dep as:

`import qrcode from 'qrcode-generator';` ?

Let me make a PR. Builds and tests run.

**Comment by souljorje** [comment]
@852Kerfunkle I already made it long time ago: https://github.com/airgap-it/beacon-sdk/pull/397

**Comment by 852Kerfunkle** [comment]
Ah, I see. Wasn't mentioned here.

What is the argument against `allowSyntheticDefaultImports` then?

**Comment by AndreasGassmann** [comment]
The UI package has changed a lot recently with the release of the new UI. Feel free to re-open this issue if it's still a problem.
