### ISSUE TITLE
Please add florencenet support

### ISSUE THREAD

**Issue by jevonearth** [airgap-it/beacon-sdk#183]
**Summary**

florencenet is the new presumptive (pending Quorum) protocol. Developers/bakers and the ecosystem needs to test against Florence to effectively evaluate it.

**Describe the expected behaviour**
The `NetworkType` enum should have

`FLORENCENET = 'florencenet'`

**Comment by AndreasGassmann** [comment]
We will release this tomorrow, along with some p2p related bugfixes.
