### ISSUE TITLE
Website error NoSuchBucket

### ISSUE THREAD

**Issue by denver-s** [airgap-it/beacon-sdk#186]
**Describe the bug (current behavior)**
Clicking on the website link on this repository page gives an error.

**To Reproduce**
1. Go to https://walletbeacon.io/

**Expected (correct) behavior**
Should redirect to https://www.walletbeacon.io/

**Screenshots and/or logs**
![image](https://user-images.githubusercontent.com/31325316/113692507-e470ec80-96cd-11eb-9b05-b5a933b8479a.png)

**Comment by AndreasGassmann** [comment]
Thanks, we'll look into it.

**Comment by pascuin** [comment]
Thanks for the headsup
