### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by geeksesi** [airgap-it/beacon-sdk#19]
hi, i want to setup beacon sdk in react and it's ok with request permission and my wallet will add to active account.
but when i want to send operation request i will get error about (The wallet does not support this network. )

this is my code :
```
import { DAppClient, NetworkType, TezosOperationType, PermissionScope } from "@airgap/beacon-sdk";

    const setUpBeacon = () => {
        const client = new DAppClient({ name: "Payzos" });
        const sendOperationRequest = () => {
            const operation = {
                kind: TezosOperationType.TRANSACTION,
                amount: amount.toString(),
                destination: address,
            };
            client
                .requestOperation({
                    operationDetails: [operation],
                })
                .then((res) => {
                    console.debug("yuuuhooo");
                })
                .catch((e) => {
                    console.debug("WE HAVE FUCKING E");
                });
        };
        const sendRequestWithoutActiveAccount = () => {
            client
                .requestPermissions({
                    network: {
                        type: NetworkType.MAINNET,
                    },
                })
                .then((permissionResponse) => {
                    if (
                        permissionResponse.scopes.some(
                            (permission) => permission === PermissionScope.OPERATION_REQUEST
                        )
                    ) {
                        sendOperationRequest();
                    }
                });
        };
        client.getActiveAccount().then((activeAccount) => {
            if (!activeAccount) {
                sendRequestWithoutActiveAccount();
            } else {
                sendOperationRequest();
            }
        });
    };

``` 

## tested envirovments :
 - chromium with Thanos wallet
 - chromium with beacon extention and airgap wallet on my phone
 - firefox with airgap wallet on my phone

my phone : android 9 with last version of airgap vault and wallet
also i have this error on airgap wallet : 
[image](https://user-images.githubusercontent.com/28778964/95438168-cb77c080-0962-11eb-87be-90d739d1c69d.png)

and from chromium : 
[image](https://user-images.githubusercontent.com/28778964/95438327-00841300-0963-11eb-9bb6-0f0f1be6398d.png)

just i don't have any idea can anyone help about this ?

**Comment by godenzim** [comment]
Hi @geeksesi,

The "The wallet does not support this network." error message seems to be misleading and what actually happens is a _run_operation_ error, which usually happens when the constructed operation is not valid for some reasons or there is a problem with the Tezos node used, at least according to the first image you linked. 

Do you always see this error or is it intermittent?

One test you could do to rule out a problem with the specific Tezos node used is to provide a custom network instead, with a url to a different node.

**Comment by geeksesi** [comment]
always i will see this error. nothing will not be changed.
so can u offer a valid node ?
we want to use it on production and people will pay something with their real wallet. have you any recommendation ?

**Comment by pascuin** [comment]
You can use for example https://tezos.giganode.io/

Make sure that you test the created operation with the run_operation command outside of any Beacon environment to get the correct error,  maybe you're setting a value already that should be calculated.

**Comment by pascuin** [comment]
@geeksesi were you able to resolve this issue?

**Comment by pascuin** [comment]
Closing this for now
