### ISSUE TITLE
Draggable warning

### ISSUE THREAD

**Issue by ungarson** [airgap-it/beacon-sdk#193]
Is it possible to make this warning draggable? Sometimes it hides the information that I need.
Or maybe at least closeable by swiping to right: look at the macos notifications as an example.
![image](https://user-images.githubusercontent.com/13982759/115470315-c7482c00-a23e-11eb-9129-23e8c5bbfe8d.png)

**Comment by AndreasGassmann** [comment]
@pascuin Do you have any suggestions here? This seems to be an issue for many dApps. A couple potential solutions:

- Allow user to define a top padding for all toast elements
- Make it draggable or add swipe to dismiss
- Add "close" button, just like on the "awaiting response" toast

**Comment by ungarson** [comment]
@AndreasGassmann any update?

**Comment by pascuin** [comment]
We will start work on revamping the UI component of the Beacon SDK, where we will refactor and simplify it. We can add this to the scope and see if it's feasible but there is no committed delivery date yet.
