### ISSUE TITLE
CSS inheritance 

### ISSUE THREAD

**Issue by Hornebom** [airgap-it/beacon-sdk#195]
**Summary**
The modal inherits global styling

**Describe the expected behaviour**
I would expect the beacon dialog to not be affected by the global styling of the site it's implemented on

**Describe your use case**
I use to define `font-size: 62.5%` on the html (The 62.5% method simplifies things for developers to see the relationships between the px value and the em or rem)

The global styling affects specifically `.beacon-selection__name`, what results in label with a really small font-size. Also spacings used in the dialog are affected if they are set in `rem/em`

**Additional context**

**Comment by AndreasGassmann** [comment]
@pascuin Is this still the case with the changes you made in https://github.com/airgap-it/beacon-sdk/pull/200/files ?

**Comment by pascuin** [comment]
No, this has addressed that.
