### ISSUE TITLE
Improve default UI

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#196]
The default UI provides some feedback of what is happening, but there are still some cases that are not handled:

1. When using taquito, initiating an operation request usually involves fetching some data (eg. entrypoints) from the chain. If the RPC calls are slow, this can sometimes take a long time (multiple seconds) where there is no feedback. People usually assume the beacon connection is slow, so they manually disconnect or try to re-do the action. To prevent this, we should create another state for the toast which is called "prepare". The sticky toast can be triggered immediately and lets the user know that something is done in the background.
2. When the "reset connection" button is clicked in the toast, the toast closes but there is no further feedback. We should show a toast that says "The connection has been reset, please pair again" for 5 seconds.
3. The "Awaiting response" toast can only be closed, but the connection cannot be reset (no dropdown). If the dApp does not provide a "disconnect" button, it is not possible to disconnect browser extension, for example. So doing any action will always trigger the extension, it is not possible to switch to a p2p wallet. Adding the dropdown to the "Awaiting response" toast would solve that.

We should also improve the mobile behaviour. Somehow we should add an option to trigger the deeplink to directly open the mobile wallet.

**Comment by jevonearth** [comment]
1. In the case of Taquito and slow RPC's, is this related to the preparation of an operation before it gets sent via Beacon?

Implementing better progress indicators in dApps (and I think Taquito has a role here to exemplify good indicators through our docs) that show if the RPC nodes (for example) are slow or non-responsive, or unsynced.

2. It would be nice to have the default beacon dialogue reachable/openable (sic). Sometimes it disappears, but I want to get it back to see what the connection state is in. Perhaps having a visual icon that is either "connected/paired" or "disconnected/not-paired" that when clicked will open the Beacon dialogue. This could be a venue to have a bug report call to action that allows the user to export some logs and device information.

**Comment by AndreasGassmann** [comment]
> In the case of Taquito and slow RPC's, is this related to the preparation of an operation before it gets sent via Beacon?

Yes. I observed this once when we were using our (newly set up) florencenet node and we had some connection issues. RPC calls would often spike and take 5 to 10 seconds, and if one of the calls was affected that happened during the preparation (eg. getting entrypoints), then there would be no feedback during that time until taquito was done and invoked the beacon send method.

What I had in mind was exposing a simple method on the DAppClient, let's call it `showPrepare()`. If that message is called, the default UI is shown with "Preparing operation...". Taquito could call this immediately whenever someone does a "send()". Then the UI would be displayed until beacon receives the request, at which point it will transition to the states we currently have.

2. I will look into this with @pascuin.

**Comment by pascuin** [comment]
> What I had in mind was exposing a simple method on the DAppClient, let's call it showPrepare()

Makes sense to me, but is this only a corner case with Taquito or in general?

> Perhaps having a visual icon that is either "connected/paired" or "disconnected/not-paired" that when clicked will open the Beacon dialogue. 

@jevonearth How and where would you see that this icon would be displayed, is this an action that the developer has to implement actievly e.g. in a settings page of the dApp?

**Comment by AndreasGassmann** [comment]
> but is this only a corner case with Taquito or in general?

It can also be an issue without taquito if the dApp needs to do some calculations/network calls before the request can be sent. In that case, the developer has to call `showPrepare()` himself, with taquito, we could make it automatic.

**Comment by AndreasGassmann** [comment]
This has been added to the beacon-sdk and taquito a while ago.
