### ISSUE TITLE
NPM library can't find 'events' module

### ISSUE THREAD

**Issue by gravitythestudio** [airgap-it/beacon-sdk#215]
**Describe the bug (current behavior)**
Receiving following error on page load when importing @airgap/beacon-sdk building a web app per both technical docs and ExampleDapp.html code examples: "Cannot find module 'events' in '@airgap/beacon-sdk/dist/esm/matrix-client"

**To Reproduce**
Code is implemented here:
https://www.gravitythestud.io/redeemwears

**Environment**
 -Wix Velo web developer (@airgap/beacon-sdk library is installed)
 - Browser : Chrome

**Comment by AndreasGassmann** [comment]
The `MatrixClient` uses the `EventEmitter`, which is not available in the browser by default. Your build system should add a polyfill for the `events` package during the build step to make it work in the browser.

What build system are you using?

You might be able to solve this by installing the `events` package explicitly using `npm i events`.

**Comment by gravitythestudio** [comment]
Thanks for responding. I’ve tried Browserify and Webpack now. Browserify wont build and Webpack has been spitting back errors about no longer creating polyfills in v5. 

>

**Comment by AndreasGassmann** [comment]
Did you install the `events` package manually? Can't you configure webpack v5 to include polyfills? Maybe with a plugin?

We also do a browserify build and publish it on unpkg, we never had problems with that build: https://github.com/airgap-it/beacon-sdk/blob/master/package.json#L27

**Comment by fredcy** [comment]
With @airgap/beacon-sdk@3.0.0 I had to `npm i events` as suggested above to get around fatal errors like this from `vite build`:

```
'EventEmitter' is not exported by __vite-browser-external, imported by node_modules/@airgap/beacon-transport-matrix/dist/esm/matrix-client/MatrixClientEventEmitter.js
file: /Users/fcy/projects/tzdapp/node_modules/@airgap/beacon-transport-matrix/dist/esm/matrix-client/MatrixClientEventEmitter.js:1:9
1: import { EventEmitter } from 'events';
            ^
2: import { keys } from '@airgap/beacon-utils';
3: import { MatrixRoomStatus } from './models/MatrixRoom';```

**Comment by AndreasGassmann** [comment]
The beacon-sdk now no longer relies on the nodejs `events` package, so this should no longer be an issue.
