### ISSUE TITLE
Generating QR code triggers an additional permissions popup

### ISSUE THREAD

**Issue by Necroskillz** [airgap-it/beacon-sdk#252]
**Describe the bug (current behavior)**
When you are on desktop and go to the QR code view, then close it and try to connect with some other wallet, you get double permission popup.

**To Reproduce**
1. Open pairing dialog (on desktop)
2. Click on Airgap Wallet (this will open the QR code)
3. Close pairing dialog
4. Open pairing dialog again
5. This time click Temple
6. Click Connect
7. You are connected, and get another popup from temple

**Expected (correct) behavior**
You should not get another popup after step 6.

**Environment**

- Device: PC
 - OS: Windows 10
 - Browser Chrome

**Comment by AndreasGassmann** [comment]
I can't seem to reproduce it. Am I doing the steps correctly?

**Environment**

- Device: Mac
- OS: MacOS (latest)
- Browser: Brave
- Beacon SDK: 2.3.1

https://user-images.githubusercontent.com/680814/128019238-3a155af9-6dd1-42d2-ad1e-c20fa173f56e.mov

**Comment by AndreasGassmann** [comment]
I will close this, feel free to re-open if this is in fact a beacon issue.
