### ISSUE TITLE
Kukai tab never opens first time on Safari

### ISSUE THREAD

**Issue by burk3** [airgap-it/beacon-sdk#257]
**Describe the bug (current behavior)**
On Safari (iOS/macOS) version 14.1.2, the first attempt to connect Kukai via Beacon will always be blocked/fail while Beacon shows "establishing connection" forever. On desktop, the user is shown a "popup blocked" message in the location bar, and on iOS the user is not shown anything. After a refresh of the page (using the browser's refresh button), the attempt to connect Kukai via Beacon will succeed in opening the new tab on both browsers.

There is one more difference between macOS and iOS, where navigating to the app's page again in a fresh tab and attempting to connect Kukai will again have the new tab blocked while on macOS it will go through (as though it has been allowed on some list).

**To Reproduce**
1. Using Safari on macOS or iOS, open a Private Window (to avoid any previous state affecting results)
2. navigate to an app using beacon (e.g. https://hicetnunc.xyz )
3. Bring up the Beacon modal (e.g. hit "sync")
4. Click on "Kukai"
5. Observe that it says "establishing connection" forever.
6. Refresh the page using the browser's refresh button.
7. Bring up the Beacon modal again (e.g. hit "sync")
8. Click on "Kukai"
9. Observe the new tab open successfully. 

**Expected (correct) behavior**
Connecting to Kukai via beacon should open Kukai in a new tab on the first attempt.

**Screenshots and/or logs**
I don't have an iOS device near me currently in order to capture any information. I can provide any logs/screenshots later this week if needed.

**Environment**

- Device: iPhone 12
 - OS: iOS 14.7.1
 - Browser: Safari 14.1.2 (current, stock browser)
- Device: M1 Macbook Pro
 - OS: macOS 11.5.2
 - Browser: Safari 14.1.2

**Additional context**
This is likely caused because the source of the event opening the new window is synthetic and untrusted event, rather than an event that is trusted and from the browser directly (i.e. the direct result of a user action, like an onClick handler or some other event dispatched inside of an onClick handler).

**Comment by AndreasGassmann** [comment]
Thanks for the report, we'll look into this.

Does it work if the user clicks on the "popup blocked" alert and then trusts it? Should that not open the previously blocked tab?

**Comment by AndreasGassmann** [comment]
This should have been resolved a while ago. Feel free to re-open if it's still not working.

**Comment by Geo25rey** [comment]
Is there a specific version of Beacon that it was fixed in? Was is it a bug on Kukai's side?

**Comment by AndreasGassmann** [comment]
It was fixed in https://github.com/airgap-it/beacon-sdk/releases/tag/v2.3.3. The issue was that the tab was opened in an async function, so it was blocked by the popup blocker.

**Comment by Geo25rey** [comment]
Sweet thanks
