### ISSUE TITLE
Temple is not detected correctly on Firefox

### ISSUE THREAD

**Issue by Necroskillz** [airgap-it/beacon-sdk#260]
**Describe the bug (current behavior)**
It seems that on firefox the extensions don't get correctly merged with the built-in wallet list, resulting in the wallet being displayed twice, once as not installed and once as installed with a different `key`.

**To Reproduce**
1. Go to app.youves.com
2. Click on Connect Wallet

**Expected (correct) behavior**
It should only display one installed browser extension.

**Screenshots and/or logs**
![image](https://user-images.githubusercontent.com/346477/131646307-3410e739-24b7-4f03-97d6-b49f502d8455.png)

![image](https://user-images.githubusercontent.com/346477/131646488-0682da07-22c4-43a6-8843-130c1004f41a.png)

**Environment**

- Device: PC
 - OS: Windows
 - Browser Firefox

**Comment by AndreasGassmann** [comment]
Yes that is indeed a case that is not handled yet. I'll see that I can fix this in the next version.

**Comment by tbinetruy** [comment]
Hi, any new on this ? We're trying to upgrade to `3.3.2` but temple isn't recognized in FF. I was recognized in `3.1.3` though.

**Comment by AndreasGassmann** [comment]
This is now done correctly in the UI.
