### ISSUE TITLE
IntercomError

### ISSUE THREAD

**Issue by andrevenancio** [airgap-it/beacon-sdk#261]
Hi!

I'm not sure exactly why this error is happening, but it seems to be coming from this module. this is the error in question:

`o {message: "Not Found", errors: undefined, name: "IntercomError"}`

If I expand the stack of this error I can see its coming from available-transport.

<img width="1177" alt="Screenshot 2021-09-01 at 17 19 52" src="https://user-images.githubusercontent.com/1734502/131707326-5d0168fc-bfb1-4d3c-8f2f-9267654e4afa.png">

I was using `airgap/beacon-sdk` directly on my codebase to have access to some Typescript types (`import { AccountInfo, Network, NetworkType } from '@airgap/beacon-sdk';`) But I've remove them from my codebase, deleted yarn.lock and re-install my dependencies and its still there, so I'm assuming its a dependency inherited from either taquito/beacon-wallet or taquito/taquito.

Either way, this error should probably not happen. Any help anyone can provide to explain what is happening?

**Comment by AndreasGassmann** [comment]
It looks like the error originates from Temple Wallet: https://github.com/madfish-solutions/templewallet-extension/search?q=intercomerror

If they send that error over postmessage, the beacon-sdk will try to handle it, so the failure to handle the message results in this error.

I am using Temple Wallet as well during development, but I've never seen this error. Do you have anything special in your setup that could explain why you get this error and I don't?

**Comment by andrevenancio** [comment]
I'll prepare a simple example to replicate it will share in the next couple of hours
