### ISSUE TITLE
Pairing with Kukai blocked

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#269]
**Describe the bug (current behavior)**
When pairing with Kukai the new browser tab will be blocked.

**To Reproduce**
1. Go to https://www.hicetnunc.xyz
2. Click on "sync" (make sure the page cache is cleared before)
3. Click on Kukai Wallet" in the list

**Expected (correct) behavior**
The Beacon SDK shouldn't behave in a way that trigger popup blockers. New tabs must be opened as a direct consequence of the button click.

**Screenshots and/or logs**
![Screenshot_58](https://user-images.githubusercontent.com/31806893/134242145-b738c6be-8d6c-43fd-9384-b57c36e88bda.jpg)

**Environment**

- Device: Mac
 - OS: Big Sur
 - Browser: Safari (14.1)

**Additional context**

**Comment by jsamol** [comment]
Hi @klassare!
We've just pushed a beta `v2.3.3-beta.0` with a fix for this. Can you check it out?

**Comment by klassare** [comment]
This fixed the problem 👍

**Comment by jsamol** [comment]
The fix has been included in `v2.3.3`.
