### ISSUE TITLE
"Request sent" toast does not show option to reset connection

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#272]
**Describe the bug (current behavior)**
"Request sent" toast does not show option to reset connection. After 5 seconds of no answer, the toast should expand and show the option.

**To Reproduce**
1. Open https://hicetnunc.xyz (desktop)
2. Pair AirGap Wallet
3. Close AirGap Wallet
4. Send another request (eg. try to buy an NFT)
5. The toast will now be stuck on "Request sent", but it will not expand after 5s.

**Expected (correct) behavior**
The toast should expand after 5s without any response from the wallet.

**Screenshots and/or logs**
<img width="345" alt="Screenshot 2021-09-23 at 09 50 37" src="https://user-images.githubusercontent.com/680814/134510322-e2a3aaaf-e3ae-4201-801e-92ca732bb932.png">

**Environment**

- Device: Macbook Air M1 / iPhone 12
- Browser: Brave

**Comment by jsamol** [comment]
Shares the same root cause as #273, fix in #275.

**Comment by AndreasGassmann** [comment]
This has been fixed.
