### ISSUE TITLE
"Open" link does not appear in toast

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#273]
**Describe the bug (current behavior)**
In a recent version of the beacon-sdk (I think 2.3.0), we introduced an "open" link in the toast that adds better UX for wallets that need to be manually opened otherwise. This is the case for Kukai and Desktop Wallets on Desktop, and for all Mobile Wallets + Kukai on Mobile.

**To Reproduce**
1. Open https://hicetnunc.xyz on mobile
2. Pair with AirGap Wallet (same device)
3. Close AirGap Wallet
4. Try to buy an NFT on hicetnunc. The "Request sent to AirGap Wallet" toast will appear, but there is no "open" link next to the AirGap Wallet name.

(The above steps can be done on Desktop, but then you have to use Kukai instead of AirGap Wallet)

**Expected (correct) behavior**
Some wallets should show an "open" link in the toast.

**Environment**

- Device: mac / iphone
- Browser: brave

**Comment by jsamol** [comment]
The cause of this issue lies in the `Request sent to...` toast not getting properly updated after the initial `Preparing Request...` is shown. As a workaround the second toast can be always forced to be created as a new. The quickfix is applied for now in #275, needs further investigating though.

**Comment by AndreasGassmann** [comment]
This has been fixed.
