### ISSUE TITLE
VITE: No matching export in "browser-external:events"

### ISSUE THREAD

**Issue by vivekascoder** [airgap-it/beacon-sdk#277]
**Describe the bug (current behavior)**

**To Reproduce**
Install beacon-sdk with taquito using Vite.

**Expected (correct) behavior**

**Screenshots and/or logs**

With React
![image](https://user-images.githubusercontent.com/54495208/134862265-4902adcb-cbf0-4b81-a566-11602f917509.png)

With Vue
![image](https://user-images.githubusercontent.com/54495208/134862041-45e68d2f-30b8-4222-885c-9ea2b6ab26fb.png)

**Environment**
Os: Linux Mint

**Comment by AndreasGassmann** [comment]
Can you try to install the "events" package manually, does that work? https://github.com/airgap-it/beacon-sdk/issues/215

**Comment by vivekascoder** [comment]
Hey i've tried installing it manually by the following command, not it is giving me this issue.
```bash
yarn add events
```

![image](https://user-images.githubusercontent.com/54495208/135875393-871e77e7-c70c-47e6-b71c-2dd78acf8c6a.png)


![image](https://user-images.githubusercontent.com/54495208/135875457-740e2bf5-edfc-4aff-81fd-58e6c2e7d0cd.png)

**Comment by noukaza** [comment]
same problem

**Comment by dpkn** [comment]
anyone figured it out? Same problem :(

**Comment by kevinelliott** [comment]
I'm having the same problem. Any solutions?

**Comment by connorgmeehan** [comment]
I found a solution here 
https://github.com/ecadlabs/taquito/issues/882#issuecomment-999753605

I changed it to use 
```typescript
defineConfig({
    optimizeDeps: {
      esbuildOptions: {
        define: {
          global: 'globalThis'
        },
      }
    },
})
```
Instead of doing this in index.html and it's working for me!

**Comment by AndreasGassmann** [comment]
We no longer rely on the `events` package, so this issue should be solved.

**Comment by xsfunc** [comment]
@AndreasGassmann not sure about this

I use vite. When import DappClient get this error:
![image](https://user-images.githubusercontent.com/91132595/184211719-3b4c94f8-f7c6-4dba-8cad-625e14ffd7d5.png)
