### ISSUE TITLE
How to handle multiple extensions / wallets

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#28]
**Summary**
The handling of multiple extensions / wallets should be improved.

**Describe the expected behaviour**
The user of a dApp should have the option to select which wallet he wants to connect to.

We are proposing a change in the flow when a permission request is sent.

Instead of the permission request immediately sending a request to the currently active transport, there will be a new UI element that is shown that will show a list of all browser extensions, as well as the P2P option. If the user clicks on either "Thanos" or "Beacon Extension", then the UI element will be closed and the permission request will only be sent to one of the extensions and there should not be any issues with both extensions trying to handle the same requests.

If the user chooses the P2P option, then the QR code (+ deeplinking options) will be shown and the user can connect any beacon compatible wallet.

**For simplicity, I suggest that we only allow one P2P wallet to be connected at a time. If the user wants to connect to another wallet, then the existing wallet has to be disconnected.**

The permission request is sent and a response is received, it is no longer necessary to show this UI element to select the destination, because we know where the subsequent requests have to be sent. Only if the user does another permission request, the wallet selection UI element will be shown again.

**Describe your use case**
This change should handle the following use cases:

- User has no extension installed and pairs a P2P wallet, then installs an extension. => Next permission request will show the "selection" UI element with the option to either connect to the extension, or use the P2P wallet.
- User has 2 extensions installed and opens a dApp for the first time and connects an account. => Permission request will show "selection" UI element with both extensions and P2P wallet as an option.
- User has extension installed and paired, then removes the extension and does a permission request. => On page load, it is detected that the chrome extension is not installed anymore and will unset the active account. So a new permission request will trigger the P2P (QR) pairing.

**Additional context**
The way how browser extensions can be detected has been discussed before and was also shared with Thanos wallet.
https://github.com/airgap-it/beacon-sdk/issues/16

**Comment by zamrokk** [comment]
Hi @AndreasGassmann , in the scope of Layer2 , we will need to have 2 wallets at the same time. One for the Layer1 and one for the Layer 2

You can see an example here on Ethereum :  https://starkgate.starknet.io/

**Comment by AndreasGassmann** [comment]
The discussion about L2s is happening here, for reference: https://github.com/airgap-it/beacon-sdk/issues/112
