### ISSUE TITLE
Large payload requests fails

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#280]
**Describe the bug (current behavior)**
Tried to send a payload request from a dapp to Kukai. According to the toast notification the request was sent to Kukai. But since an error was returned the message was obviously never sent to Kukai.

**To Reproduce**
1. Go to a Beacon test dapp
2. Send a 13.647 kB payload over the P2P transport

**Expected (correct) behavior**
It should be possible to send larger payload requests. The toast notification should not say that the request was sent to Kukai when it wasn't.

**Screenshots and/or logs**
![Screenshot_74](https://user-images.githubusercontent.com/31806893/135445061-262e084d-be28-4dad-8855-328225c6b17a.jpg)
![Screenshot_75](https://user-images.githubusercontent.com/31806893/135445076-efb16177-8d35-4ec1-af9e-136bc08f696e.jpg)

**Environment**
N/A

**Additional context**

**Comment by AndreasGassmann** [comment]
We have changed a config on all our servers, so the limit should now be higher and handle all contract originations.
