### ISSUE TITLE
About the event of beacon modal close icon

### ISSUE THREAD

**Issue by JJJJHao** [airgap-it/beacon-sdk#281]
Sorry I'm not sure if there is a forum to ask questions, so I post an issue here.
I would like to ask how to know that the user pressed the close icon on the beacon modal. 

![image](https://user-images.githubusercontent.com/6951146/136180406-f37671ec-06c9-4ef3-b357-b1e6b882f226.png)

As following, I tried to use then/catch but they are both not working.
Hope you can help me solve this problem.

```
const network = {
  type: 'mainnet',
  rpcUrl: 'https://mainnet.smartpy.io',
}
const wallet = new BeaconWallet({
  name: 'name'
})

await wallet.requestPermissions({ network })
.then((response) => {
   console.log(response)
})
.catch((e) => console.error(e))
```

Using package version : "@taquito/beacon-wallet": "^8.1.1"

**Comment by mattdesl** [comment]
Hello, running into a similar problem here. Standard flow is to 'await' the requestPermissions call, but when the close button is pressed, the promise is never resolved or rejected, so it is easy to get the app into a stuck state this way. The only option I can see for the moment without digging into the Beacon library is to set a timeout; if the user hasn't connected within say 5 seconds, we assume they closed this dialog and the promise will reject. This is a pretty poor solution as it can lead to other issues; ideally it should be solved at beacon library level.
