### ISSUE TITLE
requestOperation without re-requesting permissions with multiple accounts

### ISSUE THREAD

**Issue by andrey-shostik** [airgap-it/beacon-sdk#289]
**Summary**
My question is about requestingOperation without re-requesting permissions in case if no active account or the active account is different from the that which supposed to perform the tezosOperation like this https://paste.ofcode.org/eU9MhTRTaSiVjz8tmbDNCy

**Describe the expected behaviour**
My expected behaviour is for example to be able connect airgap and kukai wallet in app and then be able to request operation with any previously connected wallet without re-requesting permissions again. Is It reachable? Probably we could keep several accounts as active insted of the single one and then just select specific. Or are some other solutions possible?

It might look something like this
1. Connect first wallet airgap `await dAppClient.requestPermissions();`
2. Connect secod wallet kukai `await dAppClient.requestPermissions();`
3. Request operation with first airgap wallet `dAppClient.requestOperation(tezosOperation);`

But before adding second wallet we have to clearActiveAccount. That will require us to requestPermissions for interactions with airgap what actually i'm trying to eliminate

**Comment by AndreasGassmann** [comment]
This is already possible.

While there can only ever be one "active account", all the accounts / permissions that were shared are stored locally. All you have to do is set the right account as active. You can get a list of all the known accounts by using `dAppClient.getAccounts()` (see [here](https://typedocs.walletbeacon.io/classes/dappclient.html#getaccounts)), then select the account you want and call `dAppClient.setActiveAccount(account)` before sending the operation.
