### ISSUE TITLE
Add idiazabalnet support

### ISSUE THREAD

**Issue by jevonearth** [airgap-it/beacon-sdk#294]
**Summary**

The `idiazabalnet` testnet is now up and running. This net has many changes, including tenderbake. We must promote engagement with the Tezos development ecosystem so that we have more miles and eyes on this significant protocol update.

Please add support for `idiazabalnet` so that developers can easily develop and test against this new test network.

More info on this network is available here: https://teztnets.xyz/idiazabalnet-about
Public RPC nodes are available here: https://idiazabalnet.ecadinfra.com/

**Comment by AndreasGassmann** [comment]
Added in 2.3.7
