### ISSUE TITLE
Npm install @airgap/beacon-sdk fails

### ISSUE THREAD

**Issue by InfiniteSwerve** [airgap-it/beacon-sdk#298]
**Describe the bug (current behavior)**
Installing beacon-sdk results in high severity vulnerabilities because of dependencies on a previous version of axios. These cannot be fixed with npm audit fix --force, as it will introduce new breaking changes, causing the dependency structure to alternate between two broken states (see below)

**To Reproduce**
1. mkdir reproduce
2. npm install @airgap/beacon-sdk

**Expected (correct) behavior**
Added <x> packages and found 0 vulnerabilities.

**Actual Behavior**
```
...
2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```
Running `npm audit fix` results in the following:
```
...
# npm audit report

axios  <=0.21.1
Severity: high
Incorrect Comparison in axios - https://github.com/advisories/GHSA-cph5-m8f7-6c5x
fix available via `npm audit fix --force`
Will install @airgap/beacon-sdk@0.3.0, which is a breaking change
node_modules/axios
  @airgap/beacon-sdk  >=0.4.0-beta.0
  Depends on vulnerable versions of axios
  node_modules/@airgap/beacon-sdk

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

Running `npm audit fix --force` results in:
```
...
# npm audit report

matrix-js-sdk  <12.4.1
Severity: moderate
matrix-js-sdk can be tricked into disclosing E2EE room keys to a participating homeserver - https://github.com/advisories/GHSA-23cm-x6j7-6hq3
fix available via `npm audit fix --force`
Will install @airgap/beacon-sdk@2.3.7, which is a breaking change
node_modules/matrix-js-sdk
  @airgap/beacon-sdk  <=0.3.0
  Depends on vulnerable versions of matrix-js-sdk
  node_modules/@airgap/beacon-sdk

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

Running `npm audit fix --force` again will result in the first issue again .

**Environment**
- Device: Dell Inspiron 13
 - OS: Ubuntu 18.04

**Comment by AndreasGassmann** [comment]
This is now in `@airgap/beacon-sdk@2.4.0-beta.2`

**Comment by InfiniteSwerve** [comment]
Hi, sorry, I don't know what you mean. If you're saying install that instead, running `npm install @airgap/beacon-sdk@2.4.0-beta.2` doesn't work. If you're saying to wait until it's out of beta, then ok.
