### ISSUE TITLE
Same public key format across all the wallets

### ISSUE THREAD

**Issue by itsnamangoyal** [airgap-it/beacon-sdk#302]
**Summary**
public-key returned by wallets are not of the same format for all the wallets.

**Describe the expected behaviour**
Public key returned by wallets should be of the same format for all the wallets.

**Describe your use case**
I need to check the signed message in the backend. But I need to implement extra checks for public keys since they could be of different formats.

**Additional context**
This is the pk returned by airgap wallet c1a89704feb8b77a4e6696d2a3168eb8355cf0c4ccad1c687ffc30864730bdfa
And this is the key returned by temple and kukai wallet edpkv7Wgfj8qpUxMkSNBamsLxPKgfsnchNT6y1GVy6gA7K87yyhpJZ

**Comment by AndreasGassmann** [comment]
We have a PR open for this and it should be in the next release of AirGap Wallet
