### ISSUE TITLE
Browser Extension Temple Wallet does not detect on Server with Nginx 

### ISSUE THREAD

**Issue by njecom** [airgap-it/beacon-sdk#306]
Browser extension temple wallet does not detect on server with nginx but works on local server without nginx
Hi, 
In my local setup everything is same 

in my local setup Browser extension temple wallet is detected everytime but the same project on server with Nginx reverse proxy browser extension does not detect. 

**To Reproduce**
1. Test the airgap wallet with connect button on local setup 
2. click on connect wallet 
3. Browser extension Temple wallet detected and ready to login 
4. but same setup on server with nginx not works extension does not detect 

**Expected (correct) behavior**
It should detect Browser extension temple wallet with nginx reverese proxy. 

**Screenshots and/or logs**
Local
https://www.awesomescreenshot.com/image/19347604?key=c34a5048836c23c090f1edbdf4051505 
Server 
https://www.awesomescreenshot.com/image/19347839?key=1a2f0aa81023a65d5fc9177aec29058a

**Environment**
Node Js version 16.13.0 
npm 8.1.4  
Browser Firefox Chrome latest versions

**Comment by AndreasGassmann** [comment]
Hi. Sorry for the late reply.

I don't think this is related to nginx. It might be related to the fact that your site is not served over HTTPS. Could you enable HTTPS and try again?

**Comment by njecom** [comment]
Hi, Thank you for your reply. Yes Https was the issue.

Thanks
