### ISSUE TITLE
Allow permission requests to be sent with a pairing request

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#312]
**Summary**
Currently, pairing + permission request take two roundtrips to complete. On mobile phones where tabs might quickly be put to sleep, this can cause problems. We should allow the permission request to optionally be sent alongside the pairing request to reduce the number of roundtrips.

**Describe the expected behaviour**
The pairing request should optionally already include the permission request.

**Additional context**
This might be a bigger change because the SDK currently always assumes that the pairing is completed before any "application level logic" is started. With this improvement, this would change and the permission request would be done while the pairing is not complete.

We also have to make sure the change is backwards compatible.

**Comment by JJJJHao** [comment]
When will this function be completed? We often encounter users who are unable to approve permission.
Or what should we ask them to do if we encounter this problem before the fix is completed?
