### ISSUE TITLE
Temple Wallet is not enabled in pairing alert

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#317]
**Describe the bug (current behavior)**
For some users, the Temple Wallet entry in the pairing alert shows up as unavailable, even though the extension is installed.

**To Reproduce**
N/A

**Expected (correct) behavior**
If Temple Wallet is installed, it should show up as enabled.

**Screenshots and/or logs**
N/A

**Environment**
N/A

**Additional context**
This was reported by the Temple team.

It would be interesting if Spire is also disabled when a user is affected by this.

The detection is based on a ping/pong system. No matter how long it takes for the extension to reply, the entry should be enabled as soon as the pong is received. Because it seems that this is not the case, it could be possible that the affected users have a problem with their browser/extension setup in general.

To potentially mitigate this problem, we could simply remove the ping/pong check and always enable all known extension wallets.

**Comment by nikitaGetman** [comment]
Hi there. 
I get the same problem. 
Beacon works fine when I start my app locally or in development mode. But when I deploy it to the server and open it in the same browser as while develop - Temple wallet is unavailable.

My app repo - https://github.com/nikitaGetman/green-knight-tezos
Deployed app - http://84.201.184.103/17fdd05a


Browser Info:
Yandex | 96.0.4664.2588 (x86_64)
Version | f3b3926e84ab7e3ac4a4b4f3deec5f1a0be10597
OS | macOS Версия 10.15.7 (Выпуск 19H15)
JavaScript | V8 9.6.180.21
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 YaBrowser/22.1.0.2588 Yowser/2.5 Safari/537.36

**Comment by AndreasGassmann** [comment]
It has been a while, but I think the issue is that the page is not served over https. Other people have reported a similar issue and enabling SSL usually solved the issue.

However, this would not explain the "random" occurrences on production dApps.

I will close this issue because we do not have a way to reproduce it.
