### ISSUE TITLE
Beacon with NextJS

### ISSUE THREAD

**Issue by 0xpi-dev** [airgap-it/beacon-sdk#319]
hello guys ! 
newbie question here .... am trying to use Beacon, Taquito & nextjs ...however can't pass this error :

```
GOT MOCK POST MESSAGE { target: 'toExtension', payload: 'ping' }
GOT MOCK POST MESSAGE { target: 'toExtension', payload: 'ping' }
ReferenceError: localStorage is not defined
```

tried to use different appreaches to solve it :
1-  if (typeof window !== 'undefined')
2- "node-localstorage" package to create a scratch localstorage ...but no luck

**Comment by NishantChandla** [comment]
Hey @project0xpi,
I came across the same issue fixed it like so:

```
  const [wallet, setWallet] = useState<null | BeaconWallet>(null);

  const [Tezos, setTezos] = useState(new TezosToolkit("https://mainnet-tezos.giganode.io"))

  useEffect(() => {
    (async () => {
      if (wallet === null) {
        const _wallet = new (await import("@taquito/beacon-wallet")).BeaconWallet({ name: "Demo" });
        setWallet(_wallet)
        Tezos.setWalletProvider(_wallet);
      }
    })();
  }, []);```

**Comment by project0xpi** [comment]
hey @NishantChandla  thanks a lot ... I think this will work for me as well :D appreciated
