### ISSUE TITLE
Add support for ithacanet to Beacon SDK 

### ISSUE THREAD

**Issue by jevonearth** [airgap-it/beacon-sdk#320]
Summary

The ithacanet testnet is up and running. The ithaca proposal is anticipated to reach quroum in the promotion phase any day now.

Please add support for ithcanet so that developers can easily develop and test against this new test network.

More info on this network is available here: https://teztnets.xyz/ithacanet-about
Public RPC nodes are available here: https://ithcanetnet.ecadinfra.com/

I believe `idiazbalnet` can be removed from: https://github.com/airgap-it/beacon-sdk/blob/3462b66a3cd2c40f50202c009fe717c000f06bd1/src/types/beacon/NetworkType.ts#L8

**Comment by AndreasGassmann** [comment]
Done in 2.3.10
