### ISSUE TITLE
Want ability to disable (or default to off) the console.timeLog() messages

### ISSUE THREAD

**Issue by fredcy** [airgap-it/beacon-sdk#343]
**Summary**
Allow disabling the console.timeLog() messages. As it is, Beacon-SDK generates a lot of console output like the following every time the dApp interacts with a wallet:

```
12:10:18.473 4f87c42e-804f-1bd0-99b3-4b58e282b136: 3ms init done [index.c848019e.js:720:38643]
12:10:18.483 4f87c42e-804f-1bd0-99b3-4b58e282b136: 12ms sending index.c848019e.js:720:39397
12:10:18.490 4f87c42e-804f-1bd0-99b3-4b58e282b136: 20ms sent index.c848019e.js:720:39795
12:10:24.453 4f87c42e-804f-1bd0-99b3-4b58e282b136: 5984ms response index.c848019e.js:720:23214
12:10:24.454 4f87c42e-804f-1bd0-99b3-4b58e282b136: 5984ms - timer ended index.c848019e.js:720:23247
```

**Describe the expected behaviour**
I expect a production application / library to generate little or no output to the console except for cases of warnings and errors.
Where such output is useful in troubleshooting in the deployed apps, it should be optional.

**Describe your use case**
I can see how such data about timing might be useful to the Beacon-SDK developers, but it's just noise to the rest of us. I would appreciate having some kind of control over the output to be able to disable it. Or perhaps it's disabled by default and there is some special dApp or wallet API to enable it as needed.

**Comment by AndreasGassmann** [comment]
It is now possible to pass an error logger to the beacon-sdk. I will move those logs to the error logger as well so they can be enabled if needed, but will be off by default.
