### ISSUE TITLE
unable to install/build for development

### ISSUE THREAD

**Issue by fredcy** [airgap-it/beacon-sdk#346]
**Describe the bug (current behavior)**
When I attempt to `npm install` this project it fails.

**To Reproduce**
```
$ git clean -dxf
$ git describe
v3.0.0
$ git remote -v
origin	https://github.com/airgap-it/beacon-sdk.git (fetch)
origin	https://github.com/airgap-it/beacon-sdk.git (push)
$ npm install
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

> prepare
> npm run build


> prebuild
> ts-node --project tsconfig-cjs.json scripts/generate-wallet-list.ts

[Error: ENOENT: no such file or directory, open '/Users/fcy/vendor/beacon-sdk/packages/beacon-blockchain-tezos/src/ui/toast/toast-templates.ts'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/fcy/vendor/beacon-sdk/packages/beacon-blockchain-tezos/src/ui/toast/toast-templates.ts'
}
npm ERR! code 1
npm ERR! path /Users/fcy/vendor/beacon-sdk
npm ERR! command failed
npm ERR! command sh -c npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fcy/.npm/_logs/2022-05-15T18_30_45_349Z-debug-0.log
```

**Expected (correct) behavior**
I expected all the necessary dependencies to be installed within node_modules.

**Screenshots and/or logs**
See the above scenario for the error messages that resulted.

**Environment**
- Device: MacBook Pro
 - OS: macOS 12.3.1
 - Browser:  n/a

**Additional context**
I'm trying to build all the packages as a baseline for building and testing a PR for an enhancement.

**Comment by AndreasGassmann** [comment]
Is this error still present in the latest version? If it still doesn't work it would be interesting to see what the difference is between your local setup and the CI (github actions) setup, because there the build seems to work.

**Comment by JonathanReiss15** [comment]
I'm having the same error message in my environment as well.

**Comment by zamrokk** [comment]
Same error too

On Linux ` ubuntu with WSL2`

**Comment by AndreasGassmann** [comment]
Looks like this error also appears in the CI, but seems to run through: https://github.com/airgap-it/beacon-sdk/actions/runs/3197895098/jobs/5221723834#step:5:146

I'll take a look.

**Comment by spacecowb0y** [comment]
It seems that the file `packages/beacon-blockchain-tezos/src/ui/toast/toast-templates.ts` was deleted on this commit: [84349cb3aefed6b5ef853269977c5c9ae0958d4e](https://github.com/airgap-it/beacon-sdk/commit/84349cb3aefed6b5ef853269977c5c9ae0958d4e), restoring this file fix the build issue for me.

**Comment by spacecowb0y** [comment]
This issue is due the missing folders for the UI elements (`toast` in this case). The PR above should fix this ^^
