### ISSUE TITLE
Directly generate QR Code and bypassing the UI

### ISSUE THREAD

**Issue by florianharmel** [airgap-it/beacon-sdk#348]
Maybe it is already possible but i didn't find out how to do it.

**Summary**
For specific devices, generate directly the QR code instead of displaying the popup

**Expected behaviour**
I would love to have the possibility for a project to directly get the QR code and bypassing the popup

**Use case**
I want to connect my wallet on a device running the app through Ionic with no browser

**Comment by AndreasGassmann** [comment]
Hi, sorry for the late reply.

Yes, this is already possible. You will have to overwrite the default events in the `DAppClient` constructor to get the pairing information, which you can then use to generate the QR code.

If you are still looking for a solution, I can create a small example.
