### ISSUE TITLE
Beacon -> WalletConnect functionality

### ISSUE THREAD

**Issue by BearCooder** [airgap-it/beacon-sdk#351]
**Summary**
A Beacon -> WalletConnect bridge/adapter/wrapper

**Describe your use case**
WalletConnect is becoming the de facto standard and it would be beneficial if there is a Beacon -> WalletConnect bridge/adapter/wrapper. For easy integration of Tezos to interact with dapps etc in non native Tezos wallets.

**Additional context**
Maybe work together with WalletConnect so they add beacon?

**Comment by AndreasGassmann** [comment]
WalletConnect is now available in Beacon and used by TrustWallet.
