### ISSUE TITLE
WalletClient not working with React Native

### ISSUE THREAD

**Issue by leoparis89** [airgap-it/beacon-sdk#399]
I'm using React Native 0.68.1

When try to instantiate a wallet client I get an error regarding localstorage:

```
const client = new WalletClient({name:"my client"})

//ERROR [ReferenceError: Can't find variable: localStorage]

```

So I polyfilled local storage but now I'm getting an error concerning random byte generator:

```

import 'localstorage-polyfill'

const client = new WalletClient({name:"my client"})

//[Error: System random byte generator is not available.]

```

Is it possible to use WalletClient with React Native ?

Note: there is the lib react-native-randombytes that could be used in place of what is apparently missing but the error doesn't give me enough context to implement an eventual workaround.

Many thanks for your help

**Comment by leoparis89** [comment]
I think 'react-native-get-random-values' polyfill fixed the error.
Will update the issue after I do more in depth testing.

**Comment by AndreasGassmann** [comment]
Sorry for the late reply. Hopefully the polyfill fixed the error.
