### ISSUE TITLE
When localStorage ends up in a bad state Beacon does not handle the situation gracefully

### ISSUE THREAD

**Issue by BearCooder** [airgap-it/beacon-sdk#414]
**Describe the bug (current behavior)**
I would like to add that rich did discover that if the localStorage ended up in a bad state such as holding a null value where it shouldn't, Beacon wasn't able to handle the situation gracefully. For instance, Beacon could validate the data that it reads from localStorage instead of simply throwing this error.

`[TypeError: undefined is not an object (evaluating 'knownPeers.length')]`

**Additional context**
If you want more context or steps how to reproduce then please go into the Tezos dev slack into the beacon channel. Rich posted a bunch of messages but got no repsonse from Beacon team.

**Comment by BearCooder** [comment]
Its not the first time people had issue related to local storage.
When I try to connect, I get this error.
`
[TypeError: undefined is not an object (evaluating 'knownPeers.length')]`

I've found two references. One [here](https://github.com/airgap-it/beacon-sdk/blob/11ea1cbf7ba019bc879fcd49a45d824230cea3bf/packages/beacon-transport-matrix/src/P2PTransport.ts#L59) and one [here](https://github.com/airgap-it/beacon-sdk/blob/11ea1cbf7ba019bc879fcd49a45d824230cea3bf/packages/beacon-transport-postmessage/src/PostMessageTransport.ts#L140). Neither is wrapped with a try catch and from the error, it looks like it's throwing.

`const knownPeers = await this.getPeers()`
Shouldnt this be handled better? And I more curious if others have had to debug like this as well or take deeps dives into the source code to figure things out. WHICH should not be the case imo

**Comment by IsaccoSordo** [comment]
Hi @BearCooder,
this issue should be fixed in #545
