### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by BearCooder** [airgap-it/beacon-sdk#418]
Since I'm having matrix issues while using Beacon atm, I'm looking at the implementation and was wondering why something like https://github.com/matrix-org/matrix-js-sdk wasn't used instead? 

It looks like it was used until version 0.4.0. Can someone provide some insight on this decision?
https://docs.walletbeacon.io/CHANGELOG#internals-1

Thanks!

**Comment by AndreasGassmann** [comment]
The `matrix-js-sdk` provides a lot of functionality that we don't need. By adding only the functionality we needed, we were able to reduce the bundle size quite drastically.
