### ISSUE TITLE
Beacon v2 migration progress

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#45]
We will collect resources and links to test and prepare for the beacon v2 release.

## Wallets

| Wallets and libraries             | Status      | v2 branch                                                             | Link                       |
|--------------------|-------------|-----------------------------------------------------------------------|----------------------------|
| Beacon Extension   | ✅ | https://github.com/airgap-it/beacon-extension/tree/feat/beacon-v2     |[Chrome Store](https://chrome.google.com/webstore/detail/beacon-extension/gpfndedineagiepkpinficbcbbgjoenn?hl=en)|
| Thanos             | ✅ | [master](https://github.com/madfish-solutions/thanos-wallet) | [Chrome Store](https://chrome.google.com/webstore/detail/thanos-wallet/ookjlbkiijinhpmnjffcofjonbfbgaoc) |
| AirGap Wallet      | ✅ | [master](https://github.com/airgap-it/airgap-wallet) | [iOS](https://apps.apple.com/us/app/airgap-wallet/id1420996542?l=de&ls=1) / [Android](https://play.google.com/store/apps/details?id=it.airgap.wallet) |
| Kukai Wallet       | ✅ | https://github.com/kukai-wallet/kukai/tree/1.10-tzip10                | https://testnet.kukai.app/ |
| Galleon (Desktop)           | testing | https://github.com/Cryptonomic/T2/tree/develop |                            |
| Taquito (library) | ✅ | https://github.com/ecadlabs/taquito/releases/tag/7.1.0-preview.7  |                            |
| Taquito Dev Wallet | ✅ |                                                                       |                            |
| Magma           | planned |                                                                       |                            |
| Galleon (iOS)           | unknown |                                                                       |                            |
| Galleon (android)           | unknown |                                                                       |                            |

## DApps

| DApps          | Status   | v2 branch                                                            | v2 link                                          |
|---------------|----------|----------------------------------------------------------------------|--------------------------------------------------|
| Walletbeacon  | ✅  | https://github.com/airgap-it/beacon-example-dapp/tree/feat/beacon-v2 | https://papers-ch.github.io/beacon-example-dapp/ |
| Dexter        |ongoing|                                                                      |                                                  |
| Quipuswap     |unknown|                                                                      |                                                  |
| Tezos Domains |ongoing|                                                                      |                                                  |
| TzButton      |not started|                                                                      |                                                  |
| tezblock      |not started|                                                                      |                                                  |
| BetterCallDev      |unknown|                                                                      |                                                  |

## Testing for DApp Developers

```
npm i @airgap/beacon-sdk@next
```

## Open issues
https://github.com/airgap-it/beacon-sdk/milestone/1

## High level TODO:

- [ ] Create upgrade document from v1 to v2
- [ ] Create v2 changelog
- [x] Wallet selection alert testing + feedback
- [x] Disconnect and Acknowledge message testing

**Comment by pascuin** [comment]
Did some testing with the dApp https://papers-ch.github.io/beacon-example-dapp/ and Thanos, Beacon Extension on Desktop and the dApp on mobile with AirGap Wallet on Android.

The issues encountered seem not directly related with the Beacon SDK, here the high-level overview:

**Beacon Extension**
- Abort is not being sent back to dApp, user doesn't get the Beacon Alert dialog with aborted by user message. Same flow works if transaction is rejected with the Thanos Extension or AirGap Wallet

**AirGap Wallet (on Android)**
- When AirGap Wallet is closed, and Connect to Wallet is selected, AirGap Wallet prompts an "incompatible code" error after the cold start
- operation request in AirGap Wallet takes about 30s to be loaded, the page is shown with the connected dApp but the operation is only visible after some time. This did not occur consistently sometimes it loaded directly.
- Removing the permission in AirGap Wallet and then triggering a request again in the dApp resulted in no operation or error on the dApp or wallet side (afaik this functionality is not yet implemented in the SDK)

**Beacon Example dApp**
- Delphinet is not selectable for the PermissionRequest example

**Comment by pascuin** [comment]
Did some testing with the dApp https://papers-ch.github.io/beacon-example-dapp/ and Thanos, Beacon Extension on Desktop and the dApp on mobile with AirGap Wallet on Android.

The issues encountered seem not directly related with the Beacon SDK, here the high-level overview:

**AirGap Wallet (on Android)**
- [ ] When paired with Beacon Extension, the operation request pops up in AirGap Wallet, when clicking on "Continue" the page is closed but it seems that the transaction is not broadcasted, a response is also not visible in the dApp
- [ ] When scanning the QR code on https://papers-ch.github.io/beacon-example-dapp/ the dApp prompts a response but a permission request is not visible in AirGap Wallet

**Beacon Example dApp**
- [ ] When no wallet is paired and e.g. operation request is selected, I can only see a "no active account set" in the console -> would expect to see the pairing prompt like when clicking on Connect Beacon
- [ ] When pairing with AirGap Wallet the dApp shows the  alert "a browser extension has been paired" -> we need to either distinguish between wallets and browser extension in the naming for this alert or just use "A wallet has been paired"

**Comment by pascuin** [comment]
@AndreasGassmann can this be closed?
