### ISSUE TITLE
Handle rejection from wallets

### ISSUE THREAD

**Issue by kucher-mx** [airgap-it/beacon-sdk#461]
**Describe the bug (current behavior)**
Seems like not handling errors from wallet clients

**To Reproduce**
1. Start connecting or changing wallet
2. Press "Cancel" button 
3. Any interaction with wallet

**Expected (correct) behavior**
Normal interaction without crashing error

**Screenshots and/or logs**
https://shottr.cc/s/FXtw/SCR-20230314-jebp.png
https://shottr.cc/s/FgMa/SCR-20230314-jgsp.png

**Additional context**
we've posted our issue on tezos's stack exchange, so here you can see some info https://tezos.stackexchange.com/questions/4778/beacon-wallet-reading-type-error-in-dappclient-ts

**Comment by IsaccoSordo** [comment]
Hi @kucher-mx,
this issue should be addressed in #542
