### ISSUE TITLE
Wallet selection modal not closing after pairing

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#476]
**Describe the bug (current behavior)**
Wallet modal will not close after (wc2) pairing.

**To Reproduce**
1. Go to example dapp
2. Click request permission
3. Click Kukai

**Expected (correct) behavior**
After selecting a wallet the wallet selection modal should be closed. Keeping it up will only causing problem. If a user clicks a 2th time on a modal it will fail anyways, since the pairing already exist.

**Environment**

- Device: MacBook Pro
 - OS: macOS Ventura
 - Browser: Chrome

**Additional context**
Beacon version: 4.0.1-beta-kukai-wc2.0

**Comment by klassare** [comment]
Let me be more specific. After clicking on Kukai in the wallet selection modal and when the permission request show up in Kukai. At that stage the modal should close. Right now it's closed at this stage when using the p2p transport, but remains open when the wc2 transport is being used.

**Comment by mlaeng** [comment]
This should have been resolved in this beta version 4.0.6-beta.0, see: https://www.npmjs.com/package/@airgap/beacon-sdk/v/4.0.6-beta.0
