### ISSUE TITLE
Incorrect permission response

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#477]
**Describe the bug (current behavior)**
Incorrect permission responses when dapp make a permission request after initial wc2 proposal have been approved. As a consequence, it's not possible to change active account without redoing the deeplink pairing every time.

**To Reproduce**
1. Go to example dapp
2. pair and approve permission request in Kukai.
3. Send a new permission request

**Expected (correct) behavior**
A permission request should be sent to wallet when the dapp sends a permission request, and Beacon should under no circumstances return permission responses that have not been sent from the wallet. To a user this might look like the wallet is acting on it self.

**Environment**

- Device: MacBook Pro
 - OS: macOS Ventura
 - Browser: Chrome

**Additional context**
Beacon version: 4.0.1-beta-kukai-wc2.0

**Comment by mlaeng** [comment]
This should have been resolved in this beta version 4.0.6-beta.0, see: https://www.npmjs.com/package/@airgap/beacon-sdk/v/4.0.6-beta.0

**Comment by jsamol** [comment]
As already mentioned, the issue should be resolved in the beta version. In case it's not, please open a new issue providing new information.
