### ISSUE TITLE
Toast notification incorrectly saying that the wallet haven't received a request

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#478]
**Describe the bug (current behavior)**
When sending an operation request or payload request, the toast notification will say that the wallet haven't received the request, even if it have.

**To Reproduce**
1. Go to example dapp
2. Click button to sen an operation request

**Expected (correct) behavior**
Should not suggest to the user to reset the connection when wallet have successfully received the request.

**Screenshots and/or logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment**

- Device: MacBook Pro
 - OS: macOS Ventura
 - Browser: Chrome

**Additional context**
Beacon version: 4.0.1-beta-kukai-wc2.0

**Comment by AndreasGassmann** [comment]
We have to investigate if the WC2 protocol has the concept of an "acknowledge" message. If not, we may have to introduce one ourselves.

**Comment by mlaeng** [comment]
This should have been resolved in this beta version 4.0.6-beta.0, see: https://www.npmjs.com/package/@airgap/beacon-sdk/v/4.0.6-beta.0
