### ISSUE TITLE
No operation response or payload response back to dapp

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#479]
**Describe the bug (current behavior)**
When an operation request or payload request is approved on the wallet, there is no valid response sent back to the dapp.

**To Reproduce**
1. Go to example dapp
2. send an operation request to dapp
3. approve on wallet

**Expected (correct) behavior**
Toast notification should show that a operation/payload response have been received.

**Environment**

- Device: MacBook Pro
 - OS: macOS Ventura
 - Browser: Chrome

**Additional context**
Beacon version: 4.0.1-beta-kukai-wc2.0

**Comment by klassare** [comment]
Turns out this is something that can be fixed on the wallet side. But the documentation you have provided is very confusing and should be fixed. Spec says the return type property name should be [operations_hash](https://walletconnect-docs-git-fork-andreasgassmann-main-walletconnect1.vercel.app/2.0/advanced/rpc-reference/tezos-rpc#returns-1), example says [hash](https://walletconnect-docs-git-fork-andreasgassmann-main-walletconnect1.vercel.app/2.0/advanced/rpc-reference/tezos-rpc#example-1) and the source code says [transactionHash](https://github.com/airgap-it/beacon-sdk/blob/master/packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts#L301). For what reason did you decide to go with transaction hash in the source code? It makes zero sense to me...

**Comment by mlaeng** [comment]
This should have been resolved in this beta version 4.0.6-beta.0, see: https://www.npmjs.com/package/@airgap/beacon-sdk/v/4.0.6-beta.0
