### ISSUE TITLE
Old pairings not removed

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#480]
**Describe the bug (current behavior)**
When opening the wallet selection modal old sessions are removed, but not old pairings. This will clutter the wallet with old inactive pairings and can cause performance issues.

**To Reproduce**
1. Go to example dapp
2. Open wallet selection modal a 2th time after an initial pairing

**Expected (correct) behavior**
Should remove pairings when no longer needed

**Environment**

- Device: MacBook Pro
 - OS: macOS Ventura
 - Browser: Chrome

**Additional context**
Beacon version: 4.0.1-beta-kukai-wc2.0

**Comment by mlaeng** [comment]
This should have been resolved in this beta version 4.0.6-beta.0, see: https://www.npmjs.com/package/@airgap/beacon-sdk/v/4.0.6-beta.0
