### ISSUE TITLE
Stuck on loader in wallet selection modal forever

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#487]
**Describe the bug (current behavior)**
Loader in wallet selection will get stuck forever if `wcpaylouad` [sic] doesn't resolve for some reason.

**To Reproduce**
not easily reproducible

**Expected (correct) behavior**
catch and handle errors, maybe use a timeout as well

**Screenshots and/or logs**
![Skärmavbild 2023-05-04 kl  12 13 36](https://user-images.githubusercontent.com/31806893/236178340-750e973e-dcf1-4f46-a3fb-e19cd026302b.png)

**Environment**
- Device: MacBook Pro
- OS: macOS Ventura
- Browser: Chrome

**Comment by klassare** [comment]
![Skärmavbild 2023-05-04 kl  12 32 32](https://user-images.githubusercontent.com/31806893/236180035-a1f50b15-e06f-4481-bb77-ef39094f2d85.png)
This bug is very stick. Closing the modal and reopen it doesn't resolve the issue. Refreshing the page doesn't resolve the issue either.

**Comment by IsaccoSordo** [comment]
Hi @klassare, 
this issue should be addressed in #542.
