### ISSUE TITLE
Missing wallet name in toast

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#488]
**Describe the bug (current behavior)**
No wallet name or logo in permission response toast notification

**To Reproduce**
1. send a permission request and approve it

**Expected (correct) behavior**
Show display wallet name in toast notification

**Screenshots and/or logs**
![Skärmavbild 2023-05-04 kl  15 00 39](https://user-images.githubusercontent.com/31806893/236212365-9a0124ab-9a71-4d90-9534-2f3457b688d2.png)

**Environment**

- Device: MacBook Pro
- OS: macOS Ventura
- Browser: Chrome

**Additional context**
Beacon version: 4.0.1-beta-kukai-wc2.0

**Comment by mlaeng** [comment]
This should have been resolved in this beta version 4.0.6-beta.0, see: https://www.npmjs.com/package/@airgap/beacon-sdk/v/4.0.6-beta.0

**Comment by jsamol** [comment]
As already mentioned, the issue should be resolved in the beta version. In case it's not, please open a new issue providing new information.
