### ISSUE TITLE
DAppClient.init returns prematurely after canceling the connection with Temple

### ISSUE THREAD

**Issue by camlspotter** [airgap-it/beacon-sdk#489]
**Describe the bug (current behavior)**

`requestPermissions()` does not pop the wallet selection up once after canceling the connection.

**To Reproduce**

1. Call `requestPermissions()`
2. The wallet selection menu pops up
3. Select Temple
4. Click Cancel in Temple dialog
5. Call `clearActiveAccount()` to enforce the wallet selection
6. Call `requestPermissions()`
7. The wallet selection menu is expected to pop up but it does not.

**Expected (correct) behavior**

The wallet selection menu is expected to pop up at step 7.

**Environment**

- Device: desktop
 - OS: Mac OS
 - Browser: Chrome

**Additional context**

I found something strange in `DAppClient.ts`:

`initInternalTransports()` thinks the initialization is done when **either** one of the transports is non-null:

```
  public async initInternalTransports(): Promise<void> {
    const keyPair = await this.keyPair

    if (this.postMessageTransport || this.p2pTransport || this.walletConnectTransport) {
      return
    }
```

In `DAppClient.init()`, just after the call of this `initInternalTransports()`, it returns immediately unless **all** of the transports have some values:

```
        await this.initInternalTransports()

        if (!this.postMessageTransport || !this.p2pTransport || !this.walletConnectTransport) {
          return
        }
```

It seems that `init()` returns prematurely and never reinitializes the transports correctly, once somehow one of the transports has a value and another is null.

The issue is gone if I change the `if` condition of `initInternalTransports()` as follows:

```
  public async initInternalTransports(): Promise<void> {
    const keyPair = await this.keyPair

    if (this.postMessageTransport && this.p2pTransport && this.walletConnectTransport) {
      return
    }
```

**Comment by IsaccoSordo** [comment]
Hi @camlspotter,
this issue should be addressed in #542 with commit 50fcadb758b4569e20dce7e5e345a650fe042bde
