### ISSUE TITLE
Infinity Wallet Web3 Browser Beacon Connect Issues

### ISSUE THREAD

**Issue by InfinityWallet** [airgap-it/beacon-sdk#490]
Hi, we have noticed that a recent change on Beacon has broken the ability for our standalone Web3 Browser to connect to DApps via injection. It seems like you now force the requirement of a browser extension ID in order to show on the extension connection list, however as a standalone web3 browser we don't have the ability to provide such an ID.

**Comment by AndreasGassmann** [comment]
Fixed in https://github.com/airgap-it/beacon-sdk/pull/499

**Comment by mlaeng** [comment]
This should have been resolved in this beta version 4.0.6-beta.0, see: https://www.npmjs.com/package/@airgap/beacon-sdk/v/4.0.6-beta.0
