### ISSUE TITLE
Missing session_update event handler

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#496]
**Describe the bug (current behavior)**
Change account on the wallet side and it wont be reflected on the dapp side.

**To Reproduce**
1. Go to example dapp
2. Pair with Kukai
3. Goto settings and change account in the session section.

**Expected (correct) behavior**
Session updates should not just be ignored

**Environment**
N/A

**Comment by mlaeng** [comment]
This should have been resolved in this beta version 4.0.6-beta.0, see: https://www.npmjs.com/package/@airgap/beacon-sdk/v/4.0.6-beta.0

**Comment by jsamol** [comment]
As already mentioned, the issue should be resolved in the beta version. In case it's not, please open a new issue providing new information.

**Comment by klassare** [comment]
Can you link to exactly where in the code you added this event handler? I don't find anything when I search for "session_update" in the repo.
