### ISSUE TITLE
"Wallet has not sent a response" toast should expand only a few seconds

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#508]
**Describe the bug (current behavior)**
In the old UI, the "reset" button was hidden for a few seconds while an acknowledgement is received. In the new UI, this functionality does not exist.

**To Reproduce**
1. Pair with Kukai
2. Close Kukai and send operation request
3. The toast will immediately show the reset button, but it should only appear after a few seconds

**Comment by mlaeng** [comment]
This should have been resolved in this beta version 4.0.6-beta.0, see: https://www.npmjs.com/package/@airgap/beacon-sdk/v/4.0.6-beta.0
