### ISSUE TITLE
WalletConnect: Modal remains open after rejection

### ISSUE THREAD

**Issue by simonmcl** [airgap-it/beacon-sdk#518]
**Describe the bug (current behavior)**
When you open the wallet selection modal, choose Trust Wallet, scan the QR code, then cancel / reject the pairing. In this situation the modal remains open, and not listening to any WC connection. If you attempt to scan the QRCode again, the wallet will open a connection, but the dApp doesn't trigger a pairing request. To the user it looks like the wallet is broken, where as the issue is the modal is not active

**To Reproduce**
1. Open modal
2. Choose trust wallet to see a WC QR Code
3. Scan the QR code
4. Trigger a WC rejection
5. Attempt to scan the same QR Code again

**Expected (correct) behavior**
The modal should dismiss. The user shouldn't be required to reject on the wallet, and then cancel the modal, it should be one action. I assume this will re-trigger opening sockets / connections etc. If not, this all needs to be refreshed too

**Comment by IsaccoSordo** [comment]
Hi @simonmcl,
this issue should be addressed in #542
