### ISSUE TITLE
Kukai window does not automatically close after authentication/signing

### ISSUE THREAD

**Issue by tylerdmace** [airgap-it/beacon-sdk#565]
**Describe the bug (current behavior)**
When authenticating via Kukai a new window is opened and remains open indefinitely -- never returning the user back to the application.

**To Reproduce**
1. Click to sign in with Kukai
2. Complete the authentication steps in the newly opened window (Kukai web wallet)
3. Observe that despite successful authentication the window will never close to return our user back to the original application

**Expected (correct) behavior**
I would expect the Kukai web wallet window to close after authentication occurs as this is normal behavior for this authentication flow.

**Screenshots and/or logs**
N/A

**Environment**

- Device: Desktop
 - OS: Windows 11 Pro
 - Browser: Chrome 116

**Additional context**
N/A

**Comment by IsaccoSordo** [comment]
Hi @tylerdmace, we decided to opt to keep the wallet's window open because sometimes the user may need to do other stuff on the wallet side (i.e like approving a transaction).

**Comment by AndreasGassmann** [comment]
Adding to that, I'm not sure if it would even be technically possible to close the new tab after signing because of browser restrictions. If it is, then it's something that we would have to decide together with Kukai. Feel free to reach out to them (Kukai) with your idea and see what they think.
