### ISSUE TITLE
export MichelineMichelsonV1Expression type

### ISSUE THREAD

**Issue by zamrokk** [airgap-it/beacon-sdk#576]
**Summary**
I need to use this type to extract some event value , but it is not exported by the library
![image](https://github.com/airgap-it/beacon-sdk/assets/2536368/c4992d0e-a857-454b-9170-3a614fd8e62e)
![image](https://github.com/airgap-it/beacon-sdk/assets/2536368/1220677f-d406-4931-a555-ce50ee656ab2)

**Describe the expected behaviour**
Please export this type on beacon-type lib then I can compile it without error

**Comment by IsaccoSordo** [comment]
Hi @zamrokk, I opened #577 for this issue.

**Comment by IsaccoSordo** [comment]
HI @zamrokk, the fix will be available from v4.0.11
