### ISSUE TITLE
No redirecting to the selected mobile wallet after trying to connect a DApp by 'DuckDuckGO' browser

### ISSUE THREAD

**Issue by NovakVlad2424** [airgap-it/beacon-sdk#585]
No redirecting to the selected mobile wallet after trying to connect a DApp by 'DuckDuckGO' browser

Preconditions:
- 'DuckDuckGo' browser is installed
- Temple Wallet Mobile is installed (or another wallet);
- Wallet is imported/created in Temple Wallet Mobile;

Steps to reproduce the behaviour:
1. Open 'DuckDuckGo' browser;
2. Go to '[objkt.com | The largest Digital Art & Collectible marketplace on Tezos](https://objkt.com/) ';
3. Try to connect to the DApp

**Expected (correct) behavior**
User is redirected to a mobile wallet (in our case to Temple Wallet Mobile) after trying to connect a DApp by DuckDuckGO browser

**Screenshots and/or logs**
<img width="317" alt="image" src="https://github.com/airgap-it/beacon-sdk/assets/95026747/0b6aa27f-8d8c-4b24-95ec-903e0e976185">

**Environment**

- Device: Redmi Note 10S
 - OS: Android 12
 - Browser 'DuckDuckGO'

**Additional context**
No redirection to the mobile wallet, empty page is opened after trying to connect.

**Comment by IsaccoSordo** [comment]
Hi @NovakVlad2424,
yes DuckDuckGo browser behaves similarly like Safari, in other words it seems it has a built-in pop up blocker.
Therefore when beacon tries to call `window.open` the browser blocks it.
In Safari a workaround is possible (by allowing popups) but I don't see such option in DuckDuckGo browser (and I can imagine why :grin:).
Therefore no quick fix is avaiable yet, you need to wait for the next Beacon release.
In any case I opened #586 for this issue

**Comment by IsaccoSordo** [comment]
Hi @NovakVlad2424, this issue should be resolved in v4.0.11
