### ISSUE TITLE
Loader stuck on wallet selection modal

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#621]
**Describe the bug (current behavior)**
This only happens sometimes. No reliable way to reproduce it found.

**To Reproduce**
1. Click on 'Permission request' from the example dapp

**Expected (correct) behavior**
It should allow you to select a wallet

**Screenshots and/or logs**
<img width="1916" alt="Screenshot 2023-10-18 kl  14 35 33" src="https://github.com/airgap-it/beacon-sdk/assets/31806893/7bc6ba37-9c83-461e-a2b0-7e6e9c1d22e0">
<img width="1916" alt="Screenshot 2023-10-18 kl  14 35 52" src="https://github.com/airgap-it/beacon-sdk/assets/31806893/110ee097-2548-4894-b62c-d12db283b975">
<img width="1916" alt="Screenshot 2023-10-18 kl  14 37 02" src="https://github.com/airgap-it/beacon-sdk/assets/31806893/de50b538-a90d-48a6-b906-766dbf03f5b3">

**Environment**

- Device: MacBook Pro
- OS: macOS Sonoma
- Browser: Chrome

**Additional context**
Branch: feat/transport-kukai-wc2

**Comment by IsaccoSordo** [comment]
Hi @klassare,
please see https://github.com/airgap-it/beacon-sdk/issues/624#issuecomment-1795085094

**Comment by IsaccoSordo** [comment]
This issue is solved since [v4.1.1](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.1.1)
