### ISSUE TITLE
Kukai button unresponsive

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#623]
**Describe the bug (current behavior)**
Nothing happens when I click on the Kukai option

**To Reproduce**
1. Go to the example dapp and pair with Kukai
2. Open the example dapp in a second tab and click 'clear active account'
3. Go back to the first tab with the example dapp and refresh the page
4. Click the 'Permission request' button and then click on 'Kukai'

**Expected (correct) behavior**
The Kukai button should never become unresponsive in the pairing flow

**Environment**

- Device: MacBook Pro
- OS: macOS Sonoma
- Browser: Chrome

**Additional context**
Branch: feat/transport-kukai-wc2

**Comment by IsaccoSordo** [comment]
Hi @klassare,
in the event a second DApp tempers with localStoarge, then WC is not capable of reacting to those changes.
What we are doing now is to fetch information from localStorage about pairings and sessions.
Relevant lines of code: 
1. [DAppClient.ts#L1755-#L1764](https://github.com/airgap-it/beacon-sdk/blob/feat/transport-kukai-wc2/packages/beacon-dapp/src/dapp-client/DAppClient.ts#L1755-#L1764)
2. [WalletConnectTransport.ts#L67-#L8](https://github.com/airgap-it/beacon-sdk/blob/feat/transport-kukai-wc2/packages/beacon-transport-walletconnect/src/WalletConnectTransport.ts#L67-#L81)

**Comment by IsaccoSordo** [comment]
This issue is solved since [v4.1.1](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.1.1)
