### ISSUE TITLE
Add try/catch when removing sessions and pairings

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#654]
**Describe the bug (current behavior)**
When removing sessions and pairings, it can happen that one fails (eg. because it doesn't exist anymore). We need to handle this.

**To Reproduce**
1. Create multiple sessions
2. Delete all of them

**Expected (correct) behavior**
All should be removed without errors and without blocking.

**Comment by IsaccoSordo** [comment]
As #657 we now await for all promise to settle (either resolve or reject)
