### ISSUE TITLE
Re-add Galleon to Beacon

### ISSUE THREAD

**Issue by KevinMehrabi** [airgap-it/beacon-sdk#680]
Galleon wallet was recently removed from Beacon. Please re-add Galleon wallet to Beacon. 

Galleon wallet needs to be available through Beacon. It was removed recently. 

This was the commit that did it. https://github.com/airgap-it/beacon-sdk/commit/b37d0ffaa130f7200ea132d27854557508996bac Please reverse this.

**Comment by IsaccoSordo** [comment]
Hello @KevinMehrabi ,
Thank you for bringing this matter to our attention.
The initial decision to remove Galleon from our supported wallets was based on its previous discontinuation of support for our SDK as per #547. 
However, in light of the recent developments I agree that it would be beneficial to revisit this decision.

**Comment by BearCooder** [comment]
Galleon is literally unusable for me, it never connects with the network and the Team behind it stopped working on it months ago. So what recent development do you mean? As I see no sense of adding it back, unless there are some things I do not know about.

**Comment by KevinMehrabi** [comment]
When was the last time you updated it? On Dec 13, 2023, at 7:27 PM, BearCoder ***@***.***> wrote:﻿
Galleon is literally unusable for me, it never connects with the network and the Team behind it stopped working on it months ago. So what recent development do you mean? As I see no sense of adding it back, unless there are some things I do not know about.

**Comment by AndreasGassmann** [comment]
This was added in v4.1.0
