### ISSUE TITLE
[Feature] Add performance monitoring

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#689]
**Summary**
To track the performance of the beacon-sdk, we want to add telemetry to the beacon-sdk.

**Describe the expected behaviour**
Limited, unpersonal data, will be reported to a backend to get an overview of how good the beacon-sdk performs.

**Describe your use case**
We would like to be able to measure the success rate of different wallets and transports. Eg. we will report every connection attempt, including the wallet that was used. On successful completion, we will report the success. This way, we can measure if one transport or wallet has a significantly lower success rate so we can detect problems earlier.

**Comment by IsaccoSordo** [comment]
We can now receive metrics from any dApps since [v4.2.0](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.2.0)
