### ISSUE TITLE
Update TezosOperation typings

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#725]
**Summary**
Every protocol upgrade, the Tezos operation typings may be updated. We have not updated our typings (located [here](https://github.com/airgap-it/beacon-sdk/tree/master/packages/beacon-types/src/types/tezos) in a while, so now it is not possible to send certain operations because of the type mismatch, without casting it to any first.

**Describe the expected behaviour**
Typings should be in sync with the taquito typings found [here](https://github.com/ecadlabs/taquito/blob/master/packages/taquito-rpc/src/types.ts)

**Describe your use case**
This issue was raised because of the lack of support for `transfer_ticket`.

**Comment by IsaccoSordo** [comment]
The new types are available in [v4.2.0](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.2.0)
