### ISSUE TITLE
ACTIVE_ACCOUNT_SET is emitted twice

### ISSUE THREAD

**Issue by AlexandrosGounis** [airgap-it/beacon-sdk#743]
**Describe the bug (current behavior)**
When using `requestPermissions` for the first time on a DApp, no `ACTIVE_ACCOUNT_SET` is emitted. If the user `disconnects` and uses a subsequent `requestPermissions` then two, identical `ACTIVE_ACCOUNT_SET` events are emitted. Duplicate messages are also emitted when users initiate an account switch event on their wallet.

**To Reproduce**
1. Use `requestPermissions` (no event will be emitted the first time)
2. Use `disconnect` or `removeAllAccounts` (an `ACTIVE_ACCOUNT_SET` event will be emitted with an empty payload)
3. Use `requestPermissions` again (two, identical `ACTIVE_ACCOUNT_SET` events will be emitted)

**Expected (correct) behavior**
`ACTIVE_ACCOUNT_SET` should only be emitted once when the active account changes. 

**Example**
```ts
client.subscribeToEvent(BeaconEvent.ACTIVE_ACCOUNT_SET, async (payload) => {
    // receives two identical messages on subsequent pairings
});
```

**Environment**
Tested on ghostnet

**Comment by IsaccoSordo** [comment]
This issue has been addressed in [v4.2.1](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.2.1)
