### ISSUE TITLE
ACK sometimes not working

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#744]
**Describe the bug (current behavior)**
ACK is not working reliably. Can show that the wallet is not responsive when it has in fact received the request.

**Screenshots and/or logs**
![Skärmavbild 2024-03-26 kl  17 10 47](https://github.com/airgap-it/beacon-sdk/assets/31806893/fe242733-1a26-4ab6-b9ab-8dca7986b653)
![Skärmavbild 2024-03-26 kl  17 11 02](https://github.com/airgap-it/beacon-sdk/assets/31806893/bde02c1e-c269-4cf3-a00f-cfdcba39a989)

**Environment**
- Chrome / Mac

**Comment by IsaccoSordo** [comment]
Hi @klassare, are you still experiencing this issue in v4.2.1

**Comment by IsaccoSordo** [comment]
The "No matching key: history" fix has been addressed in [v4.2.1](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.2.1)
