### ISSUE TITLE
Error: No matching key

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#745]
**Describe the bug (current behavior)**
WC2 error in the console

**To Reproduce**
1. Click "Request permission" in the [example dapp](https://3026e3f03644ff75c31bd56eb939d87e0513aa11--beacon-sdk.netlify.app/dapp)
2. Pair with a wallet that uses the wc2 transport
3. refresh the dapp page
4. send a request to the wallet

**Screenshots and/or logs**
![Skärmavbild 2024-03-26 kl  18 11 17](https://github.com/airgap-it/beacon-sdk/assets/31806893/2197766a-6c78-4f10-b87d-687734c78d54)

**Comment by IsaccoSordo** [comment]
Hi @klassare 
retrieving the session through `signClient.session.get(signClient.session.keys[lastIndex])` seems to help, but it doesn't completely fix the issue. From time to time I still get The "No matching key error" after a page refresh. 
I tried also reproducing it through the WalletConnect's react-app but to no avail.
I'll try open a followup issue in the WalletConnect repo, in the meantime I'm actively looking into this issue.
Thanks for all the support.
