### ISSUE TITLE
signClient not destroyed properly when reinitializing the wc2 client

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#759]
for reference see this helper function:
https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/test/shared/helpers.ts#L4

**Comment by IsaccoSordo** [comment]
@klassare thanks a lot for your contribution, this code will be added with #760

**Comment by IsaccoSordo** [comment]
The fix has been included in [v4.2.2](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.2.2)
