### ISSUE TITLE
Not working with Angular SSR

### ISSUE THREAD

**Issue by piyushmanurkar** [airgap-it/beacon-sdk#769]
Not working with Angular SSR

getting errors like

./node_modules/@airgap/beacon-ui/dist/esm/index.js:1634:28-33 - Error: export 'style' (imported as 'style') was not found in 'solid-js/web' (possible exports: Assets, Dynamic, ErrorBoundary, For, Hydration, HydrationScript, Index, Match, NoHydration, Portal, RequestContext, Show, Suspense, SuspenseList, Switch, addEventListener, createComponent, delegateEvents, escape, generateHydrationScript, getAssets, getHydrationKey, getRequestEvent, hydrate, insert, isDev, isServer, mergeProps, pipeToNodeWritable, pipeToWritable, render, renderToStream, renderToString, renderToStringAsync, resolveSSRNode, spread, ssr, ssrAttribute, ssrClassList, ssrElement, ssrHydrationKey, ssrSpread, ssrStyle, useAssets)

**Comment by IsaccoSordo** [comment]
Hi @piyushmanurkar, sorry for the late reply.
I'm closing this issue in favor of #783, please refer to that issue for further updates and discussions.
