### ISSUE TITLE
`@taquito\beacon-wallet` rejection error is another promise

### ISSUE THREAD

**Issue by Necroskillz** [airgap-it/beacon-sdk#8]
When i get an error from `@taquito/beacon-wallet`, the caught error is a promise and I have to await it again. Not sure where it gets wrapped like this (please feel free to move this issue to the relevant repo, not sure if it's somewhere in the SDK).

Example (in order to get an actual error instance):
```
        try {
            await this.wallet.requestPermissions({
                scopes: [PermissionScope.OPERATION_REQUEST, PermissionScope.SIGN],
                network: { ... },
            });
        } catch (err) {
            throw await err;
        }
```
(same for executing smart contract operations)

**Comment by AndreasGassmann** [comment]
This will be fixed in v2.
