### ISSUE TITLE
User feedback interface improvements

### ISSUE THREAD

**Issue by pascuin** [airgap-it/beacon-sdk#83]
**Summary**
The interface components of the SDK that provide feedback to the user should be improved.

**Describe the expected behaviour**
Move away from page blocking alerts to a toast approach that provides rich information without being obtrusive. 

The current approach e.g. for a successful permission request shows an alert that the user has to click away.
![image](https://user-images.githubusercontent.com/9214127/101632040-96045780-3a25-11eb-9c8d-9ab8664762b7.png)

Alternatively a toast could be displayed for a defined amount of time that provides this user feedback similar to the "Request send" toast already used.

Additionally more information can be provided now like the name of the wallet.

**Additional context**
An approach like WalletLink would be an example
![image](https://user-images.githubusercontent.com/9214127/101631652-fb0b7d80-3a24-11eb-8d01-e874b999309f.png)

**Comment by AndreasGassmann** [comment]
Largely implemented in https://github.com/airgap-it/beacon-sdk/pull/126, we're tracking the remaining issues in the PR
